<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-gb" xml:lang="en-gb"> 
<head> 
 
<meta http-equiv="content-type" content="text/html; charset=UTF-8" /> 
<meta http-equiv="content-style-type" content="text/css" /> 
<meta http-equiv="content-language" content="en-gb" /> 
<meta http-equiv="imagetoolbar" content="no" /> 
<meta name="resource-type" content="document" /> 
<meta name="distribution" content="global" /> 
<meta name="copyright" content="2000, 2002, 2005, 2007 phpBB Group" /> 
<meta name="keywords" content="" /> 
<meta name="description" content="" /> 
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" /> 
 
<title>Areopagus &bull; Index page</title> 
 
 
 
<!--
	phpBB style name: QHST
	Based on style:   Absolution, from prosilver (this is the default phpBB3 style)
	Original author:  Tom Beddard ( http://www.subBlue.com/ )
	Modified by: Christian Bullock ( http://www.ChristianBullock.com/ )
	Modified by: Eric Miller (www.theology.edu)
 
	NOTE: This page was generated by phpBB, the free open-source bulletin board package.
	      The phpBB Group is not responsible for the content of this page and forum. For more information
	      about phpBB please visit http://www.phpbb.com
--> 
 
<script type="text/javascript"> 
// <![CDATA[
	var jump_page = 'Enter the page number you wish to go to:';
	var on_page = '';
	var per_page = '';
	var base_url = '';
	var style_cookie = 'phpBBstyle';
	var style_cookie_settings = '; path=/; domain=theology.edu';
	var onload_functions = new Array();
	var onunload_functions = new Array();
 
	
 
	/**
	* Find a member
	*/
	function find_username(url)
	{
		popup(url, 760, 570, '_usersearch');
		return false;
	}
 
	/**
	* New function for handling multiple calls to window.onload and window.unload by pentapenguin
	*/
	window.onload = function()
	{
		for (var i = 0; i < onload_functions.length; i++)
		{
			eval(onload_functions[i]);
		}
	}
 
	window.onunload = function()
	{
		for (var i = 0; i < onunload_functions.length; i++)
		{
			eval(onunload_functions[i]);
		}
	}
 
// ]]>
</script> 
<script type="text/javascript" src="./styles/QHST/template/styleswitcher.js"></script> 
<script type="text/javascript" src="./styles/QHST/template/forum_fn.js"></script> 
<script type="text/javascript" src="./styles/QHST/template/tooltip.js"></script> 
<script type="text/javascript" src="./styles/QHST/template/dropdown.js"></script> 
 
<link href="./styles/QHST/theme/print.css" rel="stylesheet" type="text/css" media="print" title="printonly" /> 
<link href="./style.php?id=14&amp;lang=en&amp;sid=00a82e838450f85ce17b4d776820b779" rel="stylesheet" type="text/css" media="screen, projection" /> 
 
<link href="./styles/QHST/theme/normal.css" rel="stylesheet" type="text/css" title="A" /> 
<link href="./styles/QHST/theme/medium.css" rel="alternate stylesheet" type="text/css" title="A+" /> 
<link href="./styles/QHST/theme/large.css" rel="alternate stylesheet" type="text/css" title="A++" /> 
 
 
 
<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="./styles/QHST/theme/ie.css" />
<![endif]--> 
 
</head> 
 
<body id="phpbb" class="section-index ltr"> 
 
<div id="page-wrap"> 
 
<div id="main-sidebar"></div> 
        
        <div id="main-content"> 
 
<p class="skiplink"><a href="#start_here">Skip to content</a></p> 
<a id="top" name="top" accesskey="t"></a> 
 
<div id="wrap"> 
    <div id="header"> 
	    <div id="header-left"> 
        <a href="./index.php?sid=00a82e838450f85ce17b4d776820b779"><img src="./styles/QHST/theme/images/logo.png" width="416" height="112" alt="" /></a> 
 
		    <!--<div id="site-details">
                    Areopagus<br />
                    <span>Quartz Hill School of Theology discussion board</span>
                </div>--> 
		</div><!-- /header-left--> 
		<div id="header-right"> 
		    <div id="formbox"> 
			    
				    <form method="post" action="./ucp.php?mode=login&amp;sid=00a82e838450f85ce17b4d776820b779"> 
					    <input type="text" name="username" class="quick-login-form" title="Username" value="Username" onfocus="if (this.value == 'Username') {this.value = '';}" onblur="if (this.value == '') {this.value = 'Username';}" /> 
                        <input type="password" name="password" class="quick-login-form" title="Password" value="********" onfocus="if (this.value == '********') {this.value = '';}" onblur="if (this.value == '') {this.value = '********';}" /> 
                        <input type="submit" name="login" value="Login" class="quick-login-button" /><br /> 
                        <label for="autologin"><input type="checkbox" name="autologin" style="margin-top: -3px;" /> Log me on automatically each visit</label> 
                        <label for="viewonline"><input type="checkbox" name="viewonline" style="margin-top: -3px;" /> Hide my online status this session</label> 
                    </form> 
                
			</div><!--/formbox / search-box--> 
		</div><!--/header-right--> 
	</div><!-- /header--> 
	<div class="float-left breadcrumbs"><img src="./styles/QHST/theme/images/house.png" width="16" height="16" alt="" /> 
	    <a href="./index.php?sid=00a82e838450f85ce17b4d776820b779" accesskey="h">Board index</a> 
	</div><!-- /float-left / breadcrumbs --> 
	
	<div class="float-right"> 
	    
		<span class="breadcrumbs"><img src="./styles/QHST/theme/images/font_add.png" width="16" height="16" alt="" /> <a href="#" onclick="fontsizeup(); return false;" onkeypress="return fontsizeup(event);" title="Change font size">Change font size</a> &nbsp;</span> 
	</div> 
	<div class="clear-both" style="margin-bottom: 6px;"></div> 
	
	<div class="toolbar"> 
	    <div class="toolbar-left"> 
		    
        </div><!-- /toolbar-left --> 
        <div class="toolbar-right"> 
	        <img src="./styles/QHST/theme/images/help.png" width="16" height="16" alt="" /> <a href="./faq.php?sid=00a82e838450f85ce17b4d776820b779" title="Frequently Asked Questions">FAQ</a> 
            <img src="./styles/QHST/theme/images/magnifier.png" width="16" height="16" alt="" /> <a href="./search.php?sid=00a82e838450f85ce17b4d776820b779" title="Search">Search</a><img src="./styles/QHST/theme/images/add.png" width="16" height="16" alt="" /> <a href="./ucp.php?mode=register&amp;sid=00a82e838450f85ce17b4d776820b779">Register</a> 
            <img src="./styles/QHST/theme/images/key.png" width="16" height="16" alt="" /> <a href="./ucp.php?mode=login&amp;sid=00a82e838450f85ce17b4d776820b779" title="Login" accesskey="x">Login</a> 
        </div><!-- /toolbar-right --> 
    </div><!-- /toolbar --> 
	
	<div class="clear-both"></div> 
 
	<a name="start_here"></a> 
	<div id="page-body"> 
<div class="AdSense"> 
  <script type="text/javascript"><!--
  google_ad_client = "pub-1971528834274288";
  /* Areopagus */
  google_ad_slot = "9045468310";
  google_ad_width = 728;
  google_ad_height = 90;
  //-->
  </script> 
  <script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js"> 
  </script> 
</div> 
 
 
<p class="right">It is currently Wed Aug 18, 2010 10:47 pm</p> 
 
<ul class="linklist"> 
	
		<li><a href="./search.php?search_id=unanswered&amp;sid=00a82e838450f85ce17b4d776820b779">View unanswered posts</a> &bull; <a href="./search.php?search_id=active_topics&amp;sid=00a82e838450f85ce17b4d776820b779">View active topics</a></li> 
	
</ul> 
 
			<div class="inner"> 
			<ul class="topiclist"> 
				<li class="header"> 
                <div class="custom-cat-header"> 
                <div class="custom-cat-header-left"> 
					<dl class="icon"> 
                    
 
                    <div class="custom-cat-header-right"></div> 
						<dt><div style="padding-left: 20px; margin-top: 8px;"><a href="./viewforum.php?f=4&amp;sid=00a82e838450f85ce17b4d776820b779">Biblical Languages</a></div></dt> 
					</dl> 
                    </div> <!-- /custom-cat-header-left --> 
                    </div> <!-- custom cat header --> 
                    
				</li> 
			</ul>    <div class="custom-row"> 
			<ul class="topiclist forums"> 
	
 
		<li class="row"> 
			<dl class="icon" style="background-image: url(./styles/QHST/imageset/forum_read.gif); background-repeat: no-repeat;"> 
				<dt title="No new posts"> 
                
                
					<a href="./viewforum.php?f=2&amp;sid=00a82e838450f85ce17b4d776820b779" class="forumtitle">Greek</a><br /> 
					<span class="forum-descriptions"></span> 
					
				</dt> 
				
                <dd class="lastpost"><span> 
                    	No posts<br />&nbsp;</span> 
					</dd> 
					<dd class="topics">0<br /><span>Topics</span><dfn>Topics</dfn></dd> 
					<dd class="posts">0<br /><span>Posts</span><dfn>Posts</dfn></dd> 
				
			</dl> 
		</li> 
 
	
 
		<li class="row"> 
			<dl class="icon" style="background-image: url(./styles/QHST/imageset/forum_read.gif); background-repeat: no-repeat;"> 
				<dt title="No new posts"> 
                
                
					<a href="./viewforum.php?f=3&amp;sid=00a82e838450f85ce17b4d776820b779" class="forumtitle">Hebrew</a><br /> 
					<span class="forum-descriptions"></span> 
					
				</dt> 
				
                <dd class="lastpost"><span> 
                    	No posts<br />&nbsp;</span> 
					</dd> 
					<dd class="topics">0<br /><span>Topics</span><dfn>Topics</dfn></dd> 
					<dd class="posts">0<br /><span>Posts</span><dfn>Posts</dfn></dd> 
				
			</dl> 
		</li> 
 
	
			</ul> 
         <!-- end custom row --> 
			</div><div class="custom-foot"><div class="custom-foot-right"></div></div> 
	
<div class="stat-info" style="background-image: url('./styles/QHST/theme/images/lock.png');"> 
	<form method="post" action="./ucp.php?mode=login&amp;sid=00a82e838450f85ce17b4d776820b779" class="headerspace"> 
	<h3><a href="./ucp.php?mode=login&amp;sid=00a82e838450f85ce17b4d776820b779">Login</a>&nbsp; &bull; &nbsp;<a href="./ucp.php?mode=register&amp;sid=00a82e838450f85ce17b4d776820b779">Register</a></h3> 
		<fieldset class="quick-login"> 
			<label for="username">Username:</label>&nbsp;<input type="text" name="username" id="username" size="10" class="inputbox" title="Username" /> 
			<label for="password">Password:</label>&nbsp;<input type="password" name="password" id="password" size="10" class="inputbox" title="Password" /> 
			
				| <label for="autologin">Log me on automatically each visit <input type="checkbox" name="autologin" id="autologin" /></label> 
			
			<input type="submit" name="login" value="Login" class="button2" /> 
            <input type="hidden" name="redirect" value="./index.php?sid=00a82e838450f85ce17b4d776820b779" /> 
 
		</fieldset> 
	</form> 
</div>    
 
<div class="stat-info" style="background-image: url('./styles/QHST/theme/images/who-is-online.png');"> 
	<h3>Who is online</h3> 
	<p>In total there is <strong>1</strong> user online :: 0 registered, 0 hidden and 1 guest (based on users active over the past 5 minutes)<br />Most users ever online was <strong>4</strong> on Tue Aug 17, 2010 2:15 am<br /> <br />Registered users: No registered users
	<br /><strong>Legend: <a style="color:#AA0000" href="./memberlist.php?mode=group&amp;g=5&amp;sid=00a82e838450f85ce17b4d776820b779">Administrators</a>, <a style="color:#00AA00" href="./memberlist.php?mode=group&amp;g=4&amp;sid=00a82e838450f85ce17b4d776820b779">Global moderators</a></strong></p> 
</div> 
 
<div class="stat-info" style="background-image: url('./styles/QHST/theme/images/statistics.png');"> 
	<h3>Statistics</h3> 
	<p>Total posts <strong>0</strong> &bull; Total topics <strong>0</strong> &bull; Total members <strong>3</strong> &bull; Our newest member <strong><a href="./memberlist.php?mode=viewprofile&amp;u=4&amp;sid=00a82e838450f85ce17b4d776820b779">chronocros</a></strong></p> 
</div> 
</div> 
 
<div id="page-footer"> 
 
<div class="toolbar-footer"> 
<div class="toolbar-left" style="padding-top: 5px; height: 31px;"> 
<div class="float-left"><img src="./styles/QHST/theme/images/house.png" width="16" height="16" alt="" /> <a href="./index.php?sid=00a82e838450f85ce17b4d776820b779" accesskey="h">Board index</a> 
 
<!-- By removing the following copyright attribution to http://www.ChristianBullock.com you are violating
intellectual copyright laws. You are therefore required to leave the copyright intact, linked to http://www.christianbullock.com
 
If you don't agree to leave the style copyright in place, don't use this style  --> 
 
<br />&copy; Absolution Style by <a href="http://www.christianbullock.com">Christian Bullock</a></div></div> 
 
<!-- End of copyright notice --> 
 
<div class="float-right toolbar-bottom-right"><div class="toolbar-right" style="padding-top: 5px; height: 31px; padding-right: 5px;"><img src="./styles/QHST/theme/images/bricks.png" width="16" height="16" alt="" /> <a href="./memberlist.php?mode=leaders&amp;sid=00a82e838450f85ce17b4d776820b779">The team</a><img src="./styles/QHST/theme/images/delete.png" width="16" height="16" alt="" /> <a href="./ucp.php?mode=delete_cookies&amp;sid=00a82e838450f85ce17b4d776820b779">Delete all board cookies</a>&bull; All times are UTC <br /> 
 
<!--
	We request you retain the full copyright notice below including the link to www.phpbb.com.
	This not only gives respect to the large amount of time given freely by the developers
	but also helps build interest, traffic and use of phpBB3. If you (honestly) cannot retain
	the full copyright we ask you at least leave in place the "Powered by phpBB" line, with
	"phpBB" linked to www.phpbb.com. If you refuse to include even this then support on our
	forums may be affected.
 
	The phpBB Group : 2006
//--> 
 
Powered by <a href="http://www.phpbb.com/">phpBB</a>&copy; 2000, 2002, 2005, 2007 phpBB Group
</div> 
</div><!-- /float-right --> 
</div><!-- /footer-toolbar--> 
 
 
 
 
		
 
</div> 
 
</div> 
 
<div> 
	<a id="bottom" name="bottom" accesskey="z"></a> 
	<img src="./cron.php?cron_type=tidy_search&amp;sid=00a82e838450f85ce17b4d776820b779" width="1" height="1" alt="cron" /> 
</div> 
 
</div> <!-- /#page-content --> 
 
 
	<div id="secondary-sidebar"></div> 
    </div> <!-- /#page-wrap --> 
 </body> 
</html>