mv MyJournal/README.html.bak MyJournal/README.html
mv adminstration.htm.bak adminstration.htm
mv beyondarchive.htm.bak beyondarchive.htm
mv blogs.htm.bak blogs.htm
mv boardtrust.htm.bak boardtrust.htm
mv dandibio.htm.bak dandibio.htm
mv deacons.html.bak deacons.html
mv diatribe07.htm.bak diatribe07.htm
mv facility.htm.bak facility.htm
mv greek411.htm.bak greek411.htm
mv hebrew/hb01.htm.bak hebrew/hb01.htm
mv hebrew/hb02.htm.bak hebrew/hb02.htm
mv hebrew/hb03.htm.bak hebrew/hb03.htm
mv hebrew/hb04.htm.bak hebrew/hb04.htm
mv hebrew/hb05.htm.bak hebrew/hb05.htm
mv hebrew/hb06.htm.bak hebrew/hb06.htm
mv hebrew/hb07.htm.bak hebrew/hb07.htm
mv hebrew/hb08.htm.bak hebrew/hb08.htm
mv hebrew/hb09.htm.bak hebrew/hb09.htm
mv hebrew/hb10.htm.bak hebrew/hb10.htm
mv hebrew/hb11.htm.bak hebrew/hb11.htm
mv hebrew/hb12.htm.bak hebrew/hb12.htm
mv hebrew/hb13.htm.bak hebrew/hb13.htm
mv hebrew/hb14.htm.bak hebrew/hb14.htm
mv hebrew/hb15.htm.bak hebrew/hb15.htm
mv hebrew/hb16.htm.bak hebrew/hb16.htm
mv hebrew/hb17.htm.bak hebrew/hb17.htm
mv hebrew/hb18.htm.bak hebrew/hb18.htm
mv hebrew/hb19.htm.bak hebrew/hb19.htm
mv hebrew/hb20.htm.bak hebrew/hb20.htm
mv hebrew/hb21.htm.bak hebrew/hb21.htm
mv hebrew/hb22.htm.bak hebrew/hb22.htm
mv hebrew/hb23.htm.bak hebrew/hb23.htm
mv hebrew/hb24.htm.bak hebrew/hb24.htm
mv hebrew/hb25.htm.bak hebrew/hb25.htm
mv hebrew/hb26.htm.bak hebrew/hb26.htm
mv hebrew/hb27.htm.bak hebrew/hb27.htm
mv hebrew/hb28.htm.bak hebrew/hb28.htm
mv hebrew/hb29.htm.bak hebrew/hb29.htm
mv index_060807.html.bak index_060807.html
mv l426.htm.bak l426.htm
mv location.html.bak location.html
mv logic/logic1.htm.bak logic/logic1.htm
mv logic/logic10.htm.bak logic/logic10.htm
mv logic/logic11.htm.bak logic/logic11.htm
mv logic/logic12.htm.bak logic/logic12.htm
mv logic/logic13.htm.bak logic/logic13.htm
mv logic/logic14.htm.bak logic/logic14.htm
mv logic/logic16.htm.bak logic/logic16.htm
mv logic/logic18.htm.bak logic/logic18.htm
mv logic/logic19.htm.bak logic/logic19.htm
mv logic/logic20.htm.bak logic/logic20.htm
mv logic/logic21.htm.bak logic/logic21.htm
mv logic/logic22.htm.bak logic/logic22.htm
mv logic/logic23.htm.bak logic/logic23.htm
mv logic/logic24.htm.bak logic/logic24.htm
mv logic/logic3.htm.bak logic/logic3.htm
mv logic/logic4.htm.bak logic/logic4.htm
mv logic/logic5.htm.bak logic/logic5.htm
mv logic/logic7.htm.bak logic/logic7.htm
mv logic/logic8.htm.bak logic/logic8.htm
mv logic/logic9.htm.bak logic/logic9.htm
mv recog.htm.bak recog.htm
mv rpnbooks/rpnbooks.htm.bak rpnbooks/rpnbooks.htm
mv rpnbooks/scifi.htm.bak rpnbooks/scifi.htm
mv sermon.html.bak sermon.html
mv shopping/CCNow.htm.bak shopping/CCNow.htm
mv whatsup.html.bak whatsup.html
mv wriintro.htm.bak wriintro.htm
mv writers/index2.html.bak writers/index2.html
mv writers/index_files/index.htm.bak writers/index_files/index.htm
mv writers/index_files/~$index.htm.bak writers/index_files/~$index.htm
mv writers/pay.htm.bak writers/pay.htm
mv writers/registrationform.htm.bak writers/registrationform.htm
mv writers/update.htm.bak writers/update.htm
mv writers/~$index.htm.bak writers/~$index.htm
