<option value="Andere">Andere</option>
<option value="Aaigem">Aaigem</option>
<option value="Aalbeke">Aalbeke</option>
<option value="Aalst">Aalst</option>
<option value="Aalst (Limb.)">Aalst (Limb.)</option>
<option value="Aalter">Aalter</option>
<option value="Aarschot">Aarschot</option>
<option value="Aarsele">Aarsele</option>
<option value="Aartrijke">Aartrijke</option>
<option value="Aartselaar">Aartselaar</option>
<option value="Abée">Abée</option>
<option value="Abolens">Abolens</option>
<option value="Achel">Achel</option>
<option value="Achêne">Achêne</option>
<option value="Achet">Achet</option>
<option value="Acosse">Acosse</option>
<option value="Acoz">Acoz</option>
<option value="Adegem">Adegem</option>
<option value="Adinkerke">Adinkerke</option>
<option value="Affligem">Affligem</option>
<option value="Afsnee">Afsnee</option>
<option value="Agimont">Agimont</option>
<option value="Aineffe">Aineffe</option>
<option value="Aische-en-Refail">Aische-en-Refail</option>
<option value="Aiseau">Aiseau</option>
<option value="Aiseau-Presles">Aiseau-Presles</option>
<option value="Aisemont">Aisemont</option>
<option value="Alken">Alken</option>
<option value="Alle">Alle</option>
<option value="Alleur">Alleur</option>
<option value="Alsemberg">Alsemberg</option>
<option value="Alveringem">Alveringem</option>
<option value="Amay">Amay</option>
<option value="Amberloup">Amberloup</option>
<option value="Ambléve">Ambléve</option>
<option value="Ambly">Ambly</option>
<option value="Ambresin">Ambresin</option>
<option value="Amel">Amel</option>
<option value="Amonines">Amonines</option>
<option value="Amougies">Amougies</option>
<option value="Ampsin">Ampsin</option>
<option value="Andenne">Andenne</option>
<option value="Anderlecht">Anderlecht</option>
<option value="Anderlues">Anderlues</option>
<option value="Andrimont">Andrimont</option>
<option value="Angleur">Angleur</option>
<option value="Angre">Angre</option>
<option value="Angreau">Angreau</option>
<option value="Anhée">Anhée</option>
<option value="Anlier">Anlier</option>
<option value="Anloy">Anloy</option>
<option value="Annevoie-Rouillon ">Annevoie-Rouillon</option>
<option value="Ans">Ans</option>
<option value="Anseremme">Anseremme</option>
<option value="Anseroeul">Anseroeul</option>
<option value="Anthée">Anthée</option>
<option value="Antheit">Antheit</option>
<option value="Anthisnes">Anthisnes</option>
<option value="Antoing">Antoing</option>
<option value="Antwerpen">Antwerpen</option>
<option value="Anvaing">Anvaing</option>
<option value="Anzegem">Anzegem</option>
<option value="Appels">Appels</option>
<option value="Appelterre-Eichem">Appelterre-Eichem</option>
<option value="Arbre (Ht.)">Arbre (Ht.)</option>
<option value="Arbre (Nam.)">Arbre (Nam.)</option>
<option value="Arbrefontaine">Arbrefontaine</option>
<option value="Arc-Ainiéres">Arc-Ainiéres</option>
<option value="Archennes">Archennes</option>
<option value="Arc-Wattripont">Arc-Wattripont</option>
<option value="Ardooie">Ardooie</option>
<option value="Arendonk">Arendonk</option>
<option value="Argenteau">Argenteau</option>
<option value="Arlon">Arlon</option>
<option value="Arquennes">Arquennes</option>
<option value="Arsimont">Arsimont</option>
<option value="Arville">Arville</option>
<option value="As">As</option>
<option value="Aspelare">Aspelare</option>
<option value="Asper">Asper</option>
<option value="Asquillies">Asquillies</option>
<option value="Asse">Asse</option>
<option value="Assebroek">Assebroek</option>
<option value="Assenede">Assenede</option>
<option value="Assenois">Assenois</option>
<option value="Assent">Assent</option>
<option value="Assesse">Assesse</option>
<option value="Astene">Astene</option>
<option value="Ath">Ath</option>
<option value="Athis">Athis</option>
<option value="Athus">Athus</option>
<option value="Attenhoven">Attenhoven</option>
<option value="Attenrode">Attenrode</option>
<option value="Attert">Attert</option>
<option value="Attre">Attre</option>
<option value="Aubange">Aubange</option>
<option value="Aubechies">Aubechies</option>
<option value="Aubel">Aubel</option>
<option value="Aublain">Aublain</option>
<option value="Auby-sur-Semois">Auby-sur-Semois</option>
<option value="Auderghem">Auderghem</option>
<option value="Audregnies">Audregnies</option>
<option value="Aulnois">Aulnois</option>
<option value="Autelbas">Autelbas</option>
<option value="Autre-Eglise">Autre-Eglise</option>
<option value="Autreppe">Autreppe</option>
<option value="Auvelais">Auvelais</option>
<option value="Ave-et-Auffe">Ave-et-Auffe</option>
<option value="Avekapelle">Avekapelle</option>
<option value="Avelgem">Avelgem</option>
<option value="Avennes">Avennes</option>
<option value="Averbode">Averbode</option>
<option value="Avernas-le-Bauduin">Avernas-le-Bauduin</option>
<option value="Avin">Avin</option>
<option value="Awans">Awans</option>
<option value="Awenne">Awenne</option>
<option value="Awirs">Awirs</option>
<option value="Aye">Aye</option>
<option value="Ayeneux">Ayeneux</option>
<option value="Aywaille">Aywaille</option>
<option value="Baaigem">Baaigem</option>
<option value="Baal">Baal</option>
<option value="Baardegem">Baardegem</option>
<option value="Baarle-Hertog">Baarle-Hertog</option>
<option value="Baasrode">Baasrode</option>
<option value="Bachte-Maria-Leerne">Bachte-Maria-Leerne</option>
<option value="Baelen (Lg.)">Baelen (Lg.)</option>
<option value="Bagimont">Bagimont</option>
<option value="Baileux">Baileux</option>
<option value="Bailiévre">Bailiévre</option>
<option value="Baillamont">Baillamont</option>
<option value="Bailleul">Bailleul</option>
<option value="Baillonville">Baillonville</option>
<option value="Baisieux">Baisieux</option>
<option value="Baisy-thy">Baisy-thy</option>
<option value="Balâtre">Balâtre</option>
<option value="Balegem">Balegem</option>
<option value="Balen">Balen</option>
<option value="Bambrugge">Bambrugge</option>
<option value="Bande">Bande</option>
<option value="Barben‡on">Barben‡on</option>
<option value="Barchon">Barchon</option>
<option value="Baronville">Baronville</option>
<option value="Barry">Barry</option>
<option value="Barvaux-Condroz">Barvaux-Condroz</option>
<option value="Barvaux-sur-Ourthe">Barvaux-sur-Ourthe</option>
<option value="Basécles">Basécles</option>
<option value="Bas-Oha">Bas-Oha</option>
<option value="Basse-Bodeux">Basse-Bodeux</option>
<option value="Bassenge">Bassenge</option>
<option value="Bassevelde">Bassevelde</option>
<option value="Bassilly">Bassilly</option>
<option value="Bastogne">Bastogne</option>
<option value="Bas-Warneton">Bas-Warneton</option>
<option value="Batsheers">Batsheers</option>
<option value="Battice">Battice</option>
<option value="Battignies">Battignies</option>
<option value="Baudour">Baudour</option>
<option value="Bauffe">Bauffe</option>
<option value="Baugnies">Baugnies</option>
<option value="Baulers">Baulers</option>
<option value="Bavegem">Bavegem</option>
<option value="Bavikhove">Bavikhove</option>
<option value="Bazel">Bazel</option>
<option value="Beaufays">Beaufays</option>
<option value="Beaumont">Beaumont</option>
<option value="Beauraing">Beauraing</option>
<option value="Beausaint">Beausaint</option>
<option value="Beauvechain">Beauvechain</option>
<option value="Beauwelz">Beauwelz</option>
<option value="Beclers">Beclers</option>
<option value="Beek">Beek</option>
<option value="Beerlegem">Beerlegem</option>
<option value="Beernem">Beernem</option>
<option value="Beerse">Beerse</option>
<option value="Beersel">Beersel</option>
<option value="Beerst">Beerst</option>
<option value="Beert">Beert</option>
<option value="Beervelde">Beervelde</option>
<option value="Beerzel">Beerzel</option>
<option value="Beez">Beez</option>
<option value="Beffe">Beffe</option>
<option value="Begijnendijk">Begijnendijk</option>
<option value="Beho">Beho</option>
<option value="Beigem">Beigem</option>
<option value="Bekegem">Bekegem</option>
<option value="Bekkerzeel">Bekkerzeel</option>
<option value="Bekkevoort">Bekkevoort</option>
<option value="Belgrade">Belgrade</option>
<option value="Bellaire">Bellaire</option>
<option value="Bellecourt">Bellecourt</option>
<option value="Bellefontaine (Lux.)">Bellefontaine (Lux.)</option>
<option value="Bellefontaine (Nam.)">Bellefontaine (Nam.)</option>
<option value="Bellegem">Bellegem</option>
<option value="Bellem">Bellem</option>
<option value="Bellevaux">Bellevaux</option>
<option value="Bellevaux-Ligneuville">Bellevaux-Ligneuville</option>
<option value="Bellingen">Bellingen</option>
<option value="Beloeil">Beloeil</option>
<option value="Belsele">Belsele</option>
<option value="Ben-Ahin">Ben-Ahin</option>
<option value="Bende">Bende</option>
<option value="Berbroek">Berbroek</option>
<option value="Berchem (Antwerpen)">Berchem (Antwerpen)</option>
<option value="Berchem (O.-Vl.)">Berchem (O.-Vl.)</option>
<option value="Berendrecht">Berendrecht</option>
<option value="Berg (Bt.)">Berg (Bt.)</option>
<option value="Berg (Limb.)">Berg (Limb.)</option>
<option value="Bergilers">Bergilers</option>
<option value="Beringen">Beringen</option>
<option value="Berlaar">Berlaar</option>
<option value="Berlare">Berlare</option>
<option value="Berlingen">Berlingen</option>
<option value="Berloz">Berloz</option>
<option value="Berneau">Berneau</option>
<option value="Bernissart">Bernissart</option>
<option value="Bersillies-l'Abbaye">Bersillies-l'Abbaye</option>
<option value="Bertem">Bertem</option>
<option value="Bertogne">Bertogne</option>
<option value="Bertrée">Bertrée</option>
<option value="Bertrix">Bertrix</option>
<option value="Berzée">Berzée</option>
<option value="Beselare">Beselare</option>
<option value="Betekom">Betekom</option>
<option value="Bettincourt">Bettincourt</option>
<option value="Beuzet">Beuzet</option>
<option value="Bevel">Bevel</option>
<option value="Bever">Bever</option>
<option value="Bevercé">Bevercé</option>
<option value="Bevere">Bevere</option>
<option value="Beveren (Leie)">Beveren (Leie)</option>
<option value="Beveren (Roeselare)">Beveren (Roeselare)</option>
<option value="Beveren-aan-den-IJzer">Beveren-aan-den-IJzer</option>
<option value="Beveren-Waas">Beveren-Waas</option>
<option value="Beverlo">Beverlo</option>
<option value="Beverst">Beverst</option>
<option value="Beyne-Heusay">Beyne-Heusay</option>
<option value="Bienne-lez-Happart">Bienne-lez-Happart</option>
<option value="Bierbeek">Bierbeek</option>
<option value="Biercée">Biercée</option>
<option value="Bierges">Bierges</option>
<option value="Bierghes">Bierghes</option>
<option value="Bierset">Bierset</option>
<option value="Bierwart">Bierwart</option>
<option value="Biesme">Biesme</option>
<option value="Biesmerée">Biesmerée</option>
<option value="Biesme-sous-Thuin">Biesme-sous-Thuin</option>
<option value="Biévéne">Biévéne</option>
<option value="Biévre">Biévre</option>
<option value="Biez">Biez</option>
<option value="Bihain">Bihain</option>
<option value="Bikschote">Bikschote</option>
<option value="Bilstain">Bilstain</option>
<option value="Bilzen">Bilzen</option>
<option value="Binche">Binche</option>
<option value="Binderveld">Binderveld</option>
<option value="Binkom">Binkom</option>
<option value="Bioul">Bioul</option>
<option value="Bissegem">Bissegem</option>
<option value="Bizet">Bizet</option>
<option value="Blaasveld">Blaasveld</option>
<option value="Blaimont">Blaimont</option>
<option value="Blandain">Blandain</option>
<option value="Blanden">Blanden</option>
<option value="Blankenberge">Blankenberge</option>
<option value="Blaregnies">Blaregnies</option>
<option value="Blaton">Blaton</option>
<option value="Blaugies">Blaugies</option>
<option value="Blégny">Blégny</option>
<option value="Bléharies">Bléharies</option>
<option value="Blehen">Blehen</option>
<option value="Bleid">Bleid</option>
<option value="Bleret">Bleret</option>
<option value="Blicquy">Blicquy</option>
<option value="Bocholt">Bocholt</option>
<option value="Boechout">Boechout</option>
<option value="Boekhout">Boekhout</option>
<option value="Boekhoute">Boekhoute</option>
<option value="Boëlhe">Boëlhe</option>
<option value="Boezinge">Boezinge</option>
<option value="Bogaarden">Bogaarden</option>
<option value="Bohan">Bohan</option>
<option value="Boignée">Boignée</option>
<option value="Boirs">Boirs</option>
<option value="Bois-de-Lessines">Bois-de-Lessines</option>
<option value="Bois-de-Villers">Bois-de-Villers</option>
<option value="Bois-d'Haine">Bois-d'Haine</option>
<option value="Bois-et-Borsu">Bois-et-Borsu</option>
<option value="Bolinne">Bolinne</option>
<option value="Bolland">Bolland</option>
<option value="Bomal (Bt.)">Bomal (Bt.)</option>
<option value="Bomal-sur-Ourthe">Bomal-sur-Ourthe</option>
<option value="Bombaye">Bombaye</option>
<option value="Bommershoven">Bommershoven</option>
<option value="Boncelles">Boncelles</option>
<option value="Boneffe">Boneffe</option>
<option value="Bonheiden">Bonheiden</option>
<option value="Boninne">Boninne</option>
<option value="Bonlez">Bonlez</option>
<option value="Bonnert">Bonnert</option>
<option value="Bonneville">Bonneville</option>
<option value="Bon-Secours">Bon-Secours</option>
<option value="Bonsin">Bonsin</option>
<option value="Booischot">Booischot</option>
<option value="Booitshoeke">Booitshoeke</option>
<option value="Boom">Boom</option>
<option value="Boorsem">Boorsem</option>
<option value="Boortmeerbeek">Boortmeerbeek</option>
<option value="Borchtlombeek">Borchtlombeek</option>
<option value="Borgerhout ">Borgerhout (Antwerpen)</option>
<option value="Borgloon">Borgloon</option>
<option value="Borlez">Borlez</option>
<option value="Borlo">Borlo</option>
<option value="Borlon">Borlon</option>
<option value="Bornem">Bornem</option>
<option value="Bornival">Bornival</option>
<option value="Borsbeek (Antw.)">Borsbeek (Antw.)</option>
<option value="Borsbeke">Borsbeke</option>
<option value="Bossiére">Bossiére</option>
<option value="Bossuit">Bossuit</option>
<option value="Bossut-Gottechain">Bossut-Gottechain</option>
<option value="Bost">Bost</option>
<option value="Bothey">Bothey</option>
<option value="Bottelare">Bottelare</option>
<option value="Bouffioulx">Bouffioulx</option>
<option value="Bouge">Bouge</option>
<option value="Bougnies">Bougnies</option>
<option value="Bouillon">Bouillon</option>
<option value="Bourlers">Bourlers</option>
<option value="Bourseigne-Neuve">Bourseigne-Neuve</option>
<option value="Bourseigne-Vieille">Bourseigne-Vieille</option>
<option value="Boussoit">Boussoit</option>
<option value="Boussu">Boussu</option>
<option value="Boussu-en-Fagne">Boussu-en-Fagne</option>
<option value="Boussu-lez-Walcourt">Boussu-lez-Walcourt</option>
<option value="Bousval">Bousval</option>
<option value="Boutersem">Boutersem</option>
<option value="Bouvignes-sur-Meuse">Bouvignes-sur-Meuse</option>
<option value="Bouvignies">Bouvignies</option>
<option value="Bouwel">Bouwel</option>
<option value="Bovekerke">Bovekerke</option>
<option value="Bovelingen">Bovelingen</option>
<option value="Bovenistier">Bovenistier</option>
<option value="Bovesse">Bovesse</option>
<option value="Bovigny">Bovigny</option>
<option value="Bra">Bra</option>
<option value="Braffe">Braffe</option>
<option value="Braibant">Braibant</option>
<option value="Braine-l'Alleud">Braine-l'Alleud</option>
<option value="Braine-le-Château">Braine-le-Château</option>
<option value="Braine-le-Comte">Braine-le-Comte</option>
<option value="Braives">Braives</option>
<option value="Brakel">Brakel</option>
<option value="Branchon">Branchon</option>
<option value="Bras">Bras</option>
<option value="Brasmenil">Brasmenil</option>
<option value="Brasschaat">Brasschaat</option>
<option value="Bray">Bray</option>
<option value="Brecht">Brecht</option>
<option value="Bredene">Bredene</option>
<option value="Bree">Bree</option>
<option value="Breendonk">Breendonk</option>
<option value="Bressoux">Bressoux</option>
<option value="Brielen">Brielen</option>
<option value="Broechem">Broechem</option>
<option value="Broekom">Broekom</option>
<option value="Brucargo">Brucargo</option>
<option value="Brugelette">Brugelette</option>
<option value="Brugge">Brugge</option>
<option value="Brugge 2">Brugge 2</option>
<option value="Brûly">Brûly</option>
<option value="Brûly-de-Pesche">Brûly-de-Pesche</option>
<option value="Brunehaut">Brunehaut</option>
<option value="Brussegem">Brussegem</option>
<option value="Brussel">Brussel</option>
<option value="Brustem">Brustem</option>
<option value="Bruyelle">Bruyelle</option>
<option value="Brye">Brye</option>
<option value="Budingen">Budingen</option>
<option value="Buggenhout">Buggenhout</option>
<option value="Buissenal">Buissenal</option>
<option value="Buissonville">Buissonville</option>
<option value="Buizingen">Buizingen</option>
<option value="Buken">Buken</option>
<option value="Bullange">Bullange</option>
<option value="Bûllingen">Bûllingen</option>
<option value="Bulskamp">Bulskamp</option>
<option value="Bunsbeek">Bunsbeek</option>
<option value="Burcht">Burcht</option>
<option value="Burdinne">Burdinne</option>
<option value="Bure">Bure</option>
<option value="Burg-Reuland">Burg-Reuland</option>
<option value="Burst">Burst</option>
<option value="Bury">Bury</option>
<option value="Butgenbach">Butgenbach</option>
<option value="Buvingen">Buvingen</option>
<option value="Buvrinnes">Buvrinnes</option>
<option value="Buzenol">Buzenol</option>
<option value="Buzet">Buzet</option>
<option value="Callenelle">Callenelle</option>
<option value="Calonne">Calonne</option>
<option value="Cambron-Casteau">Cambron-Casteau</option>
<option value="Cambron-Saint-Vincent">Cambron-Saint-Vincent</option>
<option value="Carlsbourg">Carlsbourg</option>
<option value="Carniéres">Carniéres</option>
<option value="Casteau (Mons)">Casteau (Mons)</option>
<option value="Casteau (Soignies)">Casteau (Soignies)</option>
<option value="Castillon">Castillon</option>
<option value="Celles (Ht.)">Celles (Ht.)</option>
<option value="Celles (Lg.)">Celles (Lg.)</option>
<option value="Celles (Nam.)">Celles (Nam.)</option>
<option value="Cerexhe-Heuseux">Cerexhe-Heuseux</option>
<option value="Cerfontaine">Cerfontaine</option>
<option value="Céroux-Mousty">Céroux-Mousty</option>
<option value="Ch.-Notre-Dame-Louvignies">Ch.-Notre-Dame-Louvignies</option>
<option value="Chaineux">Chaineux</option>
<option value="Chairiére">Chairiére</option>
<option value="Champion">Champion</option>
<option value="Champlon">Champlon</option>
<option value="Chanly">Chanly</option>
<option value="Chantemelle">Chantemelle</option>
<option value="Chapelle-à-Oie">Chapelle-à-Oie</option>
<option value="Chapelle-à-Wattines">Chapelle-à-Wattines</option>
<option value="Chapelle-lez-Herlaimont">Chapelle-lez-Herlaimont</option>
<option value="Chapon-Seraing">Chapon-Seraing</option>
<option value="Charleroi">Charleroi</option>
<option value="Charneux">Charneux</option>
<option value="Chassepierre">Chassepierre</option>
<option value="Chastre">Chastre</option>
<option value="Chastrés">Chastrés</option>
<option value="Chastre-Villeroux-Blanmont">Chastre-Villeroux-Blanmont</option>
<option value="Châtelet">Châtelet</option>
<option value="Châtelineau">Châtelineau</option>
<option value="Châtillon">Châtillon</option>
<option value="Chaudfontaine">Chaudfontaine</option>
<option value="Chaumont-Gistoux">Chaumont-Gistoux</option>
<option value="Chênée">Chênée</option>
<option value="Cherain">Cherain</option>
<option value="Cheratte">Cheratte</option>
<option value="Chercq">Chercq</option>
<option value="Chevetogne">Chevetogne</option>
<option value="Chevron">Chevron</option>
<option value="Chiévres">Chiévres</option>
<option value="Chimay">Chimay</option>
<option value="Chiny">Chiny</option>
<option value="Chokier">Chokier</option>
<option value="Ciergnon">Ciergnon</option>
<option value="Ciney">Ciney</option>
<option value="Ciplet">Ciplet</option>
<option value="Ciply">Ciply</option>
<option value="Clabecq">Clabecq</option>
<option value="Clavier">Clavier</option>
<option value="Clermont (Lg.)">Clermont (Lg.)</option>
<option value="Clermont (Nam.)">Clermont (Nam.)</option>
<option value="Clermont-sous-Huy">Clermont-sous-Huy</option>
<option value="Cognelée">Cognelée</option>
<option value="Colfontaine">Colfontaine</option>
<option value="Comblain-au-Pont">Comblain-au-Pont</option>
<option value="Comblain-Fairon">Comblain-Fairon</option>
<option value="Comblain-la-Tour">Comblain-la-Tour</option>
<option value="Comines">Comines</option>
<option value="Comines-Warneton">Comines-Warneton</option>
<option value="Conneux">Conneux</option>
<option value="Corbais">Corbais</option>
<option value="Corbion">Corbion</option>
<option value="Cordes">Cordes</option>
<option value="Corenne">Corenne</option>
<option value="Cornesse">Cornesse</option>
<option value="Cornimont">Cornimont</option>
<option value="Corroy-le-Château">Corroy-le-Château</option>
<option value="Corroy-le-Grand">Corroy-le-Grand</option>
<option value="Corswarem">Corswarem</option>
<option value="Cortil-Noirmont">Cortil-Noirmont</option>
<option value="Cortil-Wodon">Cortil-Wodon</option>
<option value="Couillet">Couillet</option>
<option value="Courcelles">Courcelles</option>
<option value="Courriére">Courriére</option>
<option value="Cour-sur-Heure">Cour-sur-Heure</option>
<option value="Court-Saint-Etienne">Court-Saint-Etienne</option>
<option value="Couthuin">Couthuin</option>
<option value="Coutisse">Coutisse</option>
<option value="Couture-Saint-Germain">Couture-Saint-Germain</option>
<option value="Couvin">Couvin</option>
<option value="Cras-Avernas">Cras-Avernas</option>
<option value="Crehen">Crehen</option>
<option value="Crisnée">Crisnée</option>
<option value="Croix-lez-Rouveroy">Croix-lez-Rouveroy</option>
<option value="Crombach">Crombach</option>
<option value="Crupet">Crupet</option>
<option value="Cuesmes">Cuesmes</option>
<option value="Cugnon">Cugnon</option>
<option value="Cul-des-Sarts">Cul-des-Sarts</option>
<option value="Custinne">Custinne</option>
<option value="Dadizele">Dadizele</option>
<option value="Dailly">Dailly</option>
<option value="Daknam">Daknam</option>
<option value="Dalhem">Dalhem</option>
<option value="Damme">Damme</option>
<option value="Dampicourt">Dampicourt</option>
<option value="Dampremy">Dampremy</option>
<option value="Darion">Darion</option>
<option value="Daussois">Daussois</option>
<option value="Daussoulx">Daussoulx</option>
<option value="Dave">Dave</option>
<option value="Daverdisse">Daverdisse</option>
<option value="De Haan">De Haan</option>
<option value="De Klinge">De Klinge</option>
<option value="De Moeren">De Moeren</option>
<option value="De Panne">De Panne</option>
<option value="De Pinte">De Pinte</option>
<option value="Deerlijk">Deerlijk</option>
<option value="Deftinge">Deftinge</option>
<option value="Deinze">Deinze</option>
<option value="Denderbelle">Denderbelle</option>
<option value="Denderhoutem">Denderhoutem</option>
<option value="Denderleeuw">Denderleeuw</option>
<option value="Dendermonde">Dendermonde</option>
<option value="Denderwindeke">Denderwindeke</option>
<option value="Denée">Denée</option>
<option value="Dentergem">Dentergem</option>
<option value="Dergneau">Dergneau</option>
<option value="Dessel">Dessel</option>
<option value="Desselgem">Desselgem</option>
<option value="Destelbergen">Destelbergen</option>
<option value="Deurle">Deurle</option>
<option value="Deurne (Antwerpen">Deurne (Antwerpen)</option>
<option value="Deurne (Bt.)">Deurne (Bt.)</option>
<option value="Deux-Acren">Deux-Acren</option>
<option value="Dhuy">Dhuy</option>
<option value="Diegem">Diegem</option>
<option value="Diepenbeek">Diepenbeek</option>
<option value="Diest">Diest</option>
<option value="Diets-Heur">Diets-Heur</option>
<option value="Dikkebus">Dikkebus</option>
<option value="Dikkele">Dikkele</option>
<option value="Dikkelvenne">Dikkelvenne</option>
<option value="Diksmuide">Diksmuide</option>
<option value="Dilbeek">Dilbeek</option>
<option value="Dilsen">Dilsen</option>
<option value="Dinant">Dinant</option>
<option value="Dion">Dion</option>
<option value="Dion-Valmont">Dion-Valmont</option>
<option value="Dison">Dison</option>
<option value="Dochamps">Dochamps</option>
<option value="Doel">Doel</option>
<option value="Dohan">Dohan</option>
<option value="Doische">Doische</option>
<option value="Dolembreux">Dolembreux</option>
<option value="Donceel">Donceel</option>
<option value="Dongelberg">Dongelberg</option>
<option value="Donk">Donk</option>
<option value="Donstiennes">Donstiennes</option>
<option value="Dorinne">Dorinne</option>
<option value="Dormaal">Dormaal</option>
<option value="Dottenijs">Dottenijs</option>
<option value="Dottignies">Dottignies</option>
<option value="Dour">Dour</option>
<option value="Dourbes">Dourbes</option>
<option value="Dranouter">Dranouter</option>
<option value="Dréhance">Dréhance</option>
<option value="Driekapellen">Driekapellen</option>
<option value="Drieslinter">Drieslinter</option>
<option value="Drogenbos">Drogenbos</option>
<option value="Drongen">Drongen</option>
<option value="Dudzele">Dudzele</option>
<option value="Duffel">Duffel</option>
<option value="Duisburg">Duisburg</option>
<option value="Duras">Duras</option>
<option value="Durbuy">Durbuy</option>
<option value="Durnal">Durnal</option>
<option value="Dworp">Dworp</option>
<option value="Eben-Emael>"Eben-Emael</option>
<option value="Ebly>"Ebly</option>
<option value="Ecaussinnes">Ecaussinnes</option>
<option value="Ecaussinnes-d'Enghien">Ecaussinnes-d'Enghien</option>
<option value="Ecaussinnes-Lalaing">Ecaussinnes-Lalaing</option>
<option value="Edegem">Edegem</option>
<option value="Edelare">Edelare</option>
<option value="Edingen">Edingen</option>
<option value="Eeklo">Eeklo</option>
<option value="Eernegem">Eernegem</option>
<option value="Egem">Egem</option>
<option value="Eggewaartskapelle">Eggewaartskapelle</option>
<option value="Eghezée">Eghezée</option>
<option value="Ehein (Engis)">Ehein (Engis)</option>
<option value="Ehein (Neupré)">Ehein (Neupré)</option>
<option value="Eigenbilzen">Eigenbilzen</option>
<option value="Eindhout">Eindhout</option>
<option value="Eine">Eine</option>
<option value="Eisden">Eisden</option>
<option value="Eke">Eke</option>
<option value="Ekeren (Antwerpen)">Ekeren (Antwerpen)</option>
<option value="Eksaarde">Eksaarde</option>
<option value="Eksel">Eksel</option>
<option value="Elen">Elen</option>
<option value="Elene">Elene</option>
<option value="Elewijt">Elewijt</option>
<option value="Eliksem">Eliksem</option>
<option value="Elingen">Elingen</option>
<option value="Ellemelle">Ellemelle</option>
<option value="Ellezelles">Ellezelles</option>
<option value="Ellignies-lez-Frasnes">Ellignies-lez-Frasnes</option>
<option value="Ellignies-Sainte-Anne">Ellignies-Sainte-Anne</option>
<option value="Ellikom">Ellikom</option>
<option value="Elouges">Elouges</option>
<option value="Elsegem">Elsegem</option>
<option value="Elsenborn">Elsenborn</option>
<option value="Elsene">Elsene</option>
<option value="Elst">Elst</option>
<option value="Elverdinge">Elverdinge</option>
<option value="Elversele">Elversele</option>
<option value="Emblem">Emblem</option>
<option value="Embourg">Embourg</option>
<option value="Emelgem">Emelgem</option>
<option value="Emines">Emines</option>
<option value="Emptinne">Emptinne</option>
<option value="Ename">Ename</option>
<option value="Engelmanshoven">Engelmanshoven</option>
<option value="Enghien">Enghien</option>
<option value="Engis">Engis</option>
<option value="Enines">Enines</option>
<option value="Ensival">Ensival</option>
<option value="Epinois">Epinois</option>
<option value="Eppegem">Eppegem</option>
<option value="Eprave">Eprave</option>
<option value="Erbaut">Erbaut</option>
<option value="Erbisoeul">Erbisoeul</option>
<option value="Ere">Ere</option>
<option value="Erembodegem">Erembodegem</option>
<option value="Erezée">Erezée</option>
<option value="Ermeton-sur-Biert">Ermeton-sur-Biert</option>
<option value="Ernage">Ernage</option>
<option value="Erneuville">Erneuville</option>
<option value="Ernonheid">Ernonheid</option>
<option value="Erondegem">Erondegem</option>
<option value="Erpe">Erpe</option>
<option value="Erpe-Mere">Erpe-Mere</option>
<option value="Erpent">Erpent</option>
<option value="Erpion">Erpion</option>
<option value="Erps-kwerps">Erps-kwerps</option>
<option value="Erquelinnes">Erquelinnes</option>
<option value="Erquennes">Erquennes</option>
<option value="Ertvelde">Ertvelde</option>
<option value="Erwetegem">Erwetegem</option>
<option value="Escanaffles">Escanaffles</option>
<option value="Esen">Esen</option>
<option value="Esneux">Esneux</option>
<option value="Espierres">Espierres</option>
<option value="Espierres-Helchin">Espierres-Helchin</option>
<option value="Esplechin">Esplechin</option>
<option value="Esquelmes">Esquelmes</option>
<option value="Essen">Essen</option>
<option value="Essene">Essene</option>
<option value="Estaimbourg">Estaimbourg</option>
<option value="Estaimpuis">Estaimpuis</option>
<option value="Estinnes">Estinnes</option>
<option value="Estinnes-au-Mont">Estinnes-au-Mont</option>
<option value="Estinnes-au-Val">Estinnes-au-Val</option>
<option value="Etalle">Etalle</option>
<option value="Ethe">Ethe</option>
<option value="Etikhove">Etikhove</option>
<option value="Ettelgem">Ettelgem</option>
<option value="Etterbeek">Etterbeek</option>
<option value="Eugies (Colfontaine)">Eugies (Colfontaine)</option>
<option value="Eugies (Frameries)">Eugies (Frameries)</option>
<option value="Eupen">Eupen</option>
<option value="Evegnée">Evegnée</option>
<option value="Evelette">Evelette</option>
<option value="Everbeek">Everbeek</option>
<option value="Everberg">Everberg</option>
<option value="Evere">Evere</option>
<option value="Evergem">Evergem</option>
<option value="Evregnies">Evregnies</option>
<option value="Evrehailles">Evrehailles</option>
<option value="Eynatten">Eynatten</option>
<option value="Ezemaal">Ezemaal</option>
<option value="Fagnolle">Fagnolle</option>
<option value="Faimes">Faimes</option>
<option value="Falaën">Falaën</option>
<option value="Falisolle">Falisolle</option>
<option value="Fallais">Fallais</option>
<option value="Falmagne">Falmagne</option>
<option value="Falmignoul">Falmignoul</option>
<option value="Familleureux">Familleureux</option>
<option value="Farciennes">Farciennes</option>
<option value="Faulx-les-Tombes">Faulx-les-Tombes</option>
<option value="Fauroeulx">Fauroeulx</option>
<option value="Fauvillers">Fauvillers</option>
<option value="Faymonville">Faymonville</option>
<option value="Fays-les-Veneurs">Fays-les-Veneurs</option>
<option value="Fayt-le-Franc">Fayt-le-Franc</option>
<option value="Fayt-lez-Manage">Fayt-lez-Manage</option>
<option value="Felenne">Felenne</option>
<option value="Feluy">Feluy</option>
<option value="Feneur">Feneur</option>
<option value="Fernelmont">Fernelmont</option>
<option value="Ferriéres">Ferriéres</option>
<option value="Feschaux">Feschaux</option>
<option value="Fexhe-le-Haut-Clocher">Fexhe-le-Haut-Clocher</option>
<option value="Fexhe-Slins">Fexhe-Slins</option>
<option value="Filot">Filot</option>
<option value="Finnevaux">Finnevaux</option>
<option value="Fize-Fontaine">Fize-Fontaine</option>
<option value="Fize-le-Marsal">Fize-le-Marsal</option>
<option value="Flamierge">Flamierge</option>
<option value="Flavion">Flavion</option>
<option value="Flawinne">Flawinne</option>
<option value="Flémalle">Flémalle</option>
<option value="Flémalle-Grande">Flémalle-Grande</option>
<option value="Flémalle-Haute">Flémalle-Haute</option>
<option value="Flénu">Flénu</option>
<option value="Fléron">Fléron</option>
<option value="Fleurus">Fleurus</option>
<option value="Flobecq">Flobecq</option>
<option value="Flône">Flône</option>
<option value="Florée">Florée</option>
<option value="Floreffe">Floreffe</option>
<option value="Florennes">Florennes</option>
<option value="Florenville">Florenville</option>
<option value="Floriffoux">Floriffoux</option>
<option value="Flostoy">Flostoy</option>
<option value="Focant">Focant</option>
<option value="Folx-les-Caves">Folx-les-Caves</option>
<option value="Fontaine-l'Evêque">Fontaine-l'Evêque</option>
<option value="Fontaine-Valmont">Fontaine-Valmont</option>
<option value="Fontenelle">Fontenelle</option>
<option value="Fontenoille">Fontenoille</option>
<option value="Fontenoy">Fontenoy</option>
<option value="Fooz">Fooz</option>
<option value="Forchies-la-Marche">Forchies-la-Marche</option>
<option value="Forest (Ht.)">Forest (Ht.)</option>
<option value="Forêt">Forêt</option>
<option value="Forge-Philippe">Forge-Philippe</option>
<option value="Forges">Forges</option>
<option value="Forriéres">Forriéres</option>
<option value="Forville">Forville</option>
<option value="Fosse (Lg.)">Fosse (Lg.)</option>
<option value="Fosses-la-Ville">Fosses-la-Ville</option>
<option value="Fouleng">Fouleng</option>
<option value="Fourbechies">Fourbechies</option>
<option value="Fouron-le-Comte">Fouron-le-Comte</option>
<option value="Fourons">Fourons</option>
<option value="Fouron-Saint-Martin">Fouron-Saint-Martin</option>
<option value="Fouron-Saint-Pierre">Fouron-Saint-Pierre</option>
<option value="Foy-Notre-Dame">Foy-Notre-Dame</option>
<option value="Fraipont">Fraipont</option>
<option value="Fraire">Fraire</option>
<option value="Fraiture">Fraiture</option>
<option value="Frameries">Frameries</option>
<option value="Framont">Framont</option>
<option value="Franchimont">Franchimont</option>
<option value="Francorchamps">Francorchamps</option>
<option value="Franc-Waret">Franc-Waret</option>
<option value="Franiére">Franiére</option>
<option value="Frasnes (Nam.)">Frasnes (Nam.)</option>
<option value="Frasnes-lez-Buissenal">Frasnes-lez-Buissenal</option>
<option value="Frasnes-lez-Gosselies">Frasnes-lez-Gosselies</option>
<option value="Freloux">Freloux</option>
<option value="Freux">Freux</option>
<option value="Froidchapelle">Froidchapelle</option>
<option value="Froidfontaine">Froidfontaine</option>
<option value="Froidmont">Froidmont</option>
<option value="Fronville">Fronville</option>
<option value="Froyennes">Froyennes</option>
<option value="Fumal">Fumal</option>
<option value="Furfooz">Furfooz</option>
<option value="Furnaux">Furnaux</option>
<option value="Gaasbeek">Gaasbeek</option>
<option value="Gages">Gages</option>
<option value="Gallaix">Gallaix</option>
<option value="Galmaarden">Galmaarden</option>
<option value="Ganshoren">Ganshoren</option>
<option value="Gaurain-Ramecroix">Gaurain-Ramecroix</option>
<option value="Gavere">Gavere</option>
<option value="Gedinne">Gedinne</option>
<option value="Geel">Geel</option>
<option value="Geer">Geer</option>
<option value="Geest-Gérompont-Pt-Rosiére">Geest-Gérompont-Pt-Rosiére</option>
<option value="Geetbets">Geetbets</option>
<option value="Gelbressée">Gelbressée</option>
<option value="Gelinden">Gelinden</option>
<option value="Gellik">Gellik</option>
<option value="Gelrode">Gelrode</option>
<option value="Geluveld">Geluveld</option>
<option value="Geluwe">Geluwe</option>
<option value="Gembes">Gembes</option>
<option value="Gembloux">Gembloux</option>
<option value="Gemmenich">Gemmenich</option>
<option value="Genappe">Genappe</option>
<option value="Genk">Genk</option>
<option value="Genly">Genly</option>
<option value="Genoelselderen">Genoelselderen</option>
<option value="Gent">Gent</option>
<option value="Gentbrugge">Gentbrugge</option>
<option value="Gentinnes">Gentinnes</option>
<option value="Genval">Genval</option>
<option value="Geraardsbergen">Geraardsbergen</option>
<option value="Gerdingen">Gerdingen</option>
<option value="Gerin">Gerin</option>
<option value="Gérompont">Gérompont</option>
<option value="Gérouville">Gérouville</option>
<option value="Gerpinnes">Gerpinnes</option>
<option value="Gestel">Gestel</option>
<option value="Gesves">Gesves</option>
<option value="Ghislenghien">Ghislenghien</option>
<option value="Ghlin">Ghlin</option>
<option value="Ghoy">Ghoy</option>
<option value="Gibecq">Gibecq</option>
<option value="Gierle">Gierle</option>
<option value="Gijverinkhove">Gijverinkhove</option>
<option value="Gijzegem">Gijzegem</option>
<option value="Gijzelbrechtegem">Gijzelbrechtegem</option>
<option value="Gijzenzele">Gijzenzele</option>
<option value="Gilly (Charleroi)">Gilly (Charleroi)</option>
<option value="Gimnée">Gimnée</option>
<option value="Gingelom">Gingelom</option>
<option value="Gistel">Gistel</option>
<option value="Gits">Gits</option>
<option value="Givry">Givry</option>
<option value="Glabais">Glabais</option>
<option value="Glabbeek(Zuurbemde)">Glabbeek(Zuurbemde)</option>
<option value="Glain">Glain</option>
<option value="Gleixhe">Gleixhe</option>
<option value="Glimes">Glimes</option>
<option value="Glons">Glons</option>
<option value="Gochenée">Gochenée</option>
<option value="Godarville">Godarville</option>
<option value="Godinne">Godinne</option>
<option value="Godveerdegem">Godveerdegem</option>
<option value="Goé">Goé</option>
<option value="Goeferdinge">Goeferdinge</option>
<option value="Goegnies-Chaussée">Goegnies-Chaussée</option>
<option value="Goesnes">Goesnes</option>
<option value="Goetsenhoven">Goetsenhoven</option>
<option value="Gomze-Andoumont">Gomze-Andoumont</option>
<option value="Gondregnies">Gondregnies</option>
<option value="Gonrieux">Gonrieux</option>
<option value="Gontrode">Gontrode</option>
<option value="Gooik">Gooik</option>
<option value="Gorsem">Gorsem</option>
<option value="Gors-Opleeuw">Gors-Opleeuw</option>
<option value="Gosselies">Gosselies</option>
<option value="Gotem">Gotem</option>
<option value="Gottem">Gottem</option>
<option value="Gottignies">Gottignies</option>
<option value="Gougnies">Gougnies</option>
<option value="Gourdinne">Gourdinne</option>
<option value="Goutroux">Goutroux</option>
<option value="Gouvy">Gouvy</option>
<option value="Gouy-lez-Piéton">Gouy-lez-Piéton</option>
<option value="Gozée">Gozée</option>
<option value="Grâce-Berleur">Grâce-Berleur</option>
<option value="Grâce-Hollogne">Grâce-Hollogne</option>
<option value="Graide">Graide</option>
<option value="Grammene">Grammene</option>
<option value="Grand-Axhe">Grand-Axhe</option>
<option value="Grandglise">Grandglise</option>
<option value="Grand-Hallet">Grand-Hallet</option>
<option value="Grand-Halleux">Grand-Halleux</option>
<option value="Grandhan">Grandhan</option>
<option value="Grand-Leez">Grand-Leez</option>
<option value="Grand-Manil">Grand-Manil</option>
<option value="Grandmenil">Grandmenil</option>
<option value="Grandmetz">Grandmetz</option>
<option value="Grand-Rechain">Grand-Rechain</option>
<option value="Grand-Reng">Grand-Reng</option>
<option value="Grandrieu">Grandrieu</option>
<option value="Grand-Rosiére-Hottomont">Grand-Rosiére-Hottomont</option>
<option value="Grandville">Grandville</option>
<option value="Grandvoir">Grandvoir</option>
<option value="Grapfontaine">Grapfontaine</option>
<option value="Graty">Graty</option>
<option value="Graux">Graux</option>
<option value="Grazen">Grazen</option>
<option value="Grembergen">Grembergen</option>
<option value="Grez-Doiceau">Grez-Doiceau</option>
<option value="Grimbergen">Grimbergen</option>
<option value="Grimminge">Grimminge</option>
<option value="Grivegnée (Liége)">Grivegnée (Liége)</option>
<option value="Grobbendonk">Grobbendonk</option>
<option value="Groot-Bijgaarden">Groot-Bijgaarden</option>
<option value="Groot-Gelmen">Groot-Gelmen</option>
<option value="Groot-Loon">Groot-Loon</option>
<option value="Grosage">Grosage</option>
<option value="Gros-Fays">Gros-Fays</option>
<option value="Grote-Brogel">Grote-Brogel</option>
<option value="Grotenberge">Grotenberge</option>
<option value="Grote-Spouwen">Grote-Spouwen</option>
<option value="Gruitrode">Gruitrode</option>
<option value="Grune">Grune</option>
<option value="Grupont">Grupont</option>
<option value="Guignies">Guignies</option>
<option value="Guigoven">Guigoven</option>
<option value="Guirsch">Guirsch</option>
<option value="Gullegem">Gullegem</option>
<option value="Gutschoven">Gutschoven</option>
<option value="Haacht">Haacht</option>
<option value="Haaltert">Haaltert</option>
<option value="Haasdonk">Haasdonk</option>
<option value="Haasrode">Haasrode</option>
<option value="Habay">Habay</option>
<option value="Habay-la-Neuve">Habay-la-Neuve</option>
<option value="Habay-la-Vieille">Habay-la-Vieille</option>
<option value="Habergy">Habergy</option>
<option value="Haccourt">Haccourt</option>
<option value="Hachy">Hachy</option>
<option value="Hacquegnies">Hacquegnies</option>
<option value="Haillot">Haillot</option>
<option value="Haine-Saint-Paul">Haine-Saint-Paul</option>
<option value="Haine-Saint-Pierre">Haine-Saint-Pierre</option>
<option value="Hainin">Hainin</option>
<option value="Hakendover">Hakendover</option>
<option value="Halanzy">Halanzy</option>
<option value="Halen">Halen</option>
<option value="Hallaar">Hallaar</option>
<option value="Halle">Halle</option>
<option value="Halle (Kempen)">Halle (Kempen)</option>
<option value="Halle-Booienhoven">Halle-Booienhoven</option>
<option value="Halleux">Halleux</option>
<option value="Halma">Halma</option>
<option value="Halmaal">Halmaal</option>
<option value="Haltinne">Haltinne</option>
<option value="Ham">Ham</option>
<option value="Hamipré">Hamipré</option>
<option value="Hamme (Bt.)">Hamme (Bt.)</option>
<option value="Hamme (O.-Vl.)">Hamme (O.-Vl.)</option>
<option value="Hamme-Mille">Hamme-Mille</option>
<option value="Hamoir">Hamoir</option>
<option value="Hamois">Hamois</option>
<option value="Hamont">Hamont</option>
<option value="Hamont-Achel">Hamont-Achel</option>
<option value="Hampteau">Hampteau</option>
<option value="Ham-sur-Heure">Ham-sur-Heure</option>
<option value="Ham-sur-Heure/Nalinnes">Ham-sur-Heure/Nalinnes</option>
<option value="Ham-sur-Sambre">Ham-sur-Sambre</option>
<option value="Handzame">Handzame</option>
<option value="Haneffe">Haneffe</option>
<option value="Hannêche">Hannêche</option>
<option value="Hannut">Hannut</option>
<option value="Hanret">Hanret</option>
<option value="Hansbeke">Hansbeke</option>
<option value="Han-sur-Lesse">Han-sur-Lesse</option>
<option value="Hantes-Wihéries">Hantes-Wihéries</option>
<option value="Hanzinelle">Hanzinelle</option>
<option value="Hanzinne">Hanzinne</option>
<option value="Harchies">Harchies</option>
<option value="Harelbeke">Harelbeke</option>
<option value="Haren (Borgloon)">Haren (Borgloon)</option>
<option value="Haren (Brussel-stad)">Haren (Brussel-stad)</option>
<option value="Haren (Tongeren)">Haren (Tongeren)</option>
<option value="Hargimont">Hargimont</option>
<option value="Harmignies">Harmignies</option>
<option value="Harnoncourt">Harnoncourt</option>
<option value="Harre">Harre</option>
<option value="Harsin">Harsin</option>
<option value="Harveng">Harveng</option>
<option value="Harzé">Harzé</option>
<option value="Hasselt">Hasselt</option>
<option value="Hastiére">Hastiére</option>
<option value="Hastiére-Lavaux">Hastiére-Lavaux</option>
<option value="Hastiére-par-Del...">Hastiére-par-Del...</option>
<option value="Hatrival">Hatrival</option>
<option value="Haulchin">Haulchin</option>
<option value="Hauset">Hauset</option>
<option value="Haut-Fays">Haut-Fays</option>
<option value="Haut-Ittre">Haut-Ittre</option>
<option value="Haut-le-Wastia">Haut-le-Wastia</option>
<option value="Hautrage">Hautrage</option>
<option value="Havay">Havay</option>
<option value="Havelange">Havelange</option>
<option value="Haversin">Haversin</option>
<option value="Havinnes">Havinnes</option>
<option value="Havré">Havré</option>
<option value="Hechtel">Hechtel</option>
<option value="Heer">Heer</option>
<option value="Heers">Heers</option>
<option value="Hees">Hees</option>
<option value="Heestert">Heestert</option>
<option value="Heffen">Heffen</option>
<option value="Heikruis">Heikruis</option>
<option value="Heindonk">Heindonk</option>
<option value="Heinsch">Heinsch</option>
<option value="Heist-aan-Zee">Heist-aan-Zee</option>
<option value="Heist-Op-Den-Berg">Heist-Op-Den-Berg</option>
<option value="Hekelgem">Hekelgem</option>
<option value="Heks">Heks</option>
<option value="Helchin">Helchin</option>
<option value="Helchteren">Helchteren</option>
<option value="Heldergem">Heldergem</option>
<option value="Helen-Bos">Helen-Bos</option>
<option value="Helkijn">Helkijn</option>
<option value="Hellebecq">Hellebecq</option>
<option value="Hemelveerdegem">Hemelveerdegem</option>
<option value="Hemiksem">Hemiksem</option>
<option value="Hemptinne (Fernelmont)">Hemptinne (Fernelmont)</option>
<option value="Hemptinne-lez-Florennes">Hemptinne-lez-Florennes</option>
<option value="Hendrieken">Hendrieken</option>
<option value="Henis">Henis</option>
<option value="Hennuyéres">Hennuyéres</option>
<option value="Henri-Chapelle">Henri-Chapelle</option>
<option value="Henripont">Henripont</option>
<option value="Hensies">Hensies</option>
<option value="Heppen">Heppen</option>
<option value="Heppenbach">Heppenbach</option>
<option value="Heppignies">Heppignies</option>
<option value="Herbeumont">Herbeumont</option>
<option value="Herchies">Herchies</option>
<option value="Herderen">Herderen</option>
<option value="Herdersem">Herdersem</option>
<option value="Herent">Herent</option>
<option value="Herentals">Herentals</option>
<option value="Herenthout">Herenthout</option>
<option value="Herfelingen">Herfelingen</option>
<option value="Hergenrath">Hergenrath</option>
<option value="Hérinnes-lez-Pecq">Hérinnes-lez-Pecq</option>
<option value="Herk-de-Stad">Herk-de-Stad</option>
<option value="Hermalle-sous-Argenteau">Hermalle-sous-Argenteau</option>
<option value="Hermalle-sous-Huy">Hermalle-sous-Huy</option>
<option value="Hermée">Hermée</option>
<option value="Hermeton-sur-Meuse">Hermeton-sur-Meuse</option>
<option value="Herne">Herne</option>
<option value="Héron">Héron</option>
<option value="Herquegies">Herquegies</option>
<option value="Herseaux">Herseaux</option>
<option value="Herselt">Herselt</option>
<option value="Herstal">Herstal</option>
<option value="Herstappe">Herstappe</option>
<option value="Hertain">Hertain</option>
<option value="Herten">Herten</option>
<option value="Hertsberge">Hertsberge</option>
<option value="Herve">Herve</option>
<option value="Herzele">Herzele</option>
<option value="Heule">Heule</option>
<option value="Heure (Nam.)">Heure (Nam.)</option>
<option value="Heure-le-Romain">Heure-le-Romain</option>
<option value="Heurne">Heurne</option>
<option value="Heusden (Limb.)">Heusden (Limb.)</option>
<option value="Heusden (O.-Vl.)">Heusden (O.-Vl.)</option>
<option value="Heusden-Zolder">Heusden-Zolder</option>
<option value="Heusy">Heusy</option>
<option value="Hever">Hever</option>
<option value="Heverlee">Heverlee</option>
<option value="Hévillers">Hévillers</option>
<option value="Heyd">Heyd</option>
<option value="Hillegem">Hillegem</option>
<option value="Hingene">Hingene</option>
<option value="Hingeon">Hingeon</option>
<option value="Hives">Hives</option>
<option value="Hoboken (Antwerpen)">Hoboken (Antwerpen)</option>
<option value="Hodeige">Hodeige</option>
<option value="Hodister">Hodister</option>
<option value="Hody">Hody</option>
<option value="Hoegaarden">Hoegaarden</option>
<option value="Hoeilaart">Hoeilaart</option>
<option value="Hoeke">Hoeke</option>
<option value="Hoelbeek">Hoelbeek</option>
<option value="Hoeleden">Hoeleden</option>
<option value="Hoepertingen">Hoepertingen</option>
<option value="Hoeselt">Hoeselt</option>
<option value="Hoevenen">Hoevenen</option>
<option value="Hofstade (Bt.)">Hofstade (Bt.)</option>
<option value="Hofstade (O.-Vl.)">Hofstade (O.-Vl.)</option>
<option value="Hogne">Hogne</option>
<option value="Hognoul">Hognoul</option>
<option value="Hollain">Hollain</option>
<option value="Hollange">Hollange</option>
<option value="Hollebeke">Hollebeke</option>
<option value="Hollogne-aux-Pierres">Hollogne-aux-Pierres</option>
<option value="Hollogne-sur-Geer">Hollogne-sur-Geer</option>
<option value="Holsbeek">Holsbeek</option>
<option value="Hombeek">Hombeek</option>
<option value="Hombourg">Hombourg</option>
<option value="Hompré">Hompré</option>
<option value="Hondelange">Hondelange</option>
<option value="Honnay">Honnay</option>
<option value="Honnelles">Honnelles</option>
<option value="Hooglede">Hooglede</option>
<option value="Hoogstade">Hoogstade</option>
<option value="Hoogstraten">Hoogstraten</option>
<option value="Horebeke">Horebeke</option>
<option value="Horion-Hozémont">Horion-Hozémont</option>
<option value="Hornu">Hornu</option>
<option value="Horpmaal">Horpmaal</option>
<option value="Horrues">Horrues</option>
<option value="Hotton">Hotton</option>
<option value="Houdemont">Houdemont</option>
<option value="Houdeng-Aimeries">Houdeng-Aimeries</option>
<option value="Houdeng-Goegnies">Houdeng-Goegnies</option>
<option value="Houdremont">Houdremont</option>
<option value="Houffalize">Houffalize</option>
<option value="Hour">Hour</option>
<option value="Housse">Housse</option>
<option value="Houtaing">Houtaing</option>
<option value="Houtain-le-Val">Houtain-le-Val</option>
<option value="Houtain-Saint-Siméon">Houtain-Saint-Siméon</option>
<option value="Houtave">Houtave</option>
<option value="Houtem (W.-Vl.)">Houtem (W.-Vl.)</option>
<option value="Houthalen">Houthalen</option>
<option value="Houthalen-Helchteren">Houthalen-Helchteren</option>
<option value="Houthem (Comines)">Houthem (Comines)</option>
<option value="Houthulst">Houthulst</option>
<option value="Houtvenne">Houtvenne</option>
<option value="Houwaart">Houwaart</option>
<option value="Houx">Houx</option>
<option value="Houyet">Houyet</option>
<option value="Hove">Hove</option>
<option value="Hoves (Ht.)">Hoves (Ht.)</option>
<option value="Howardries">Howardries</option>
<option value="Huccorgne">Huccorgne</option>
<option value="Huise">Huise</option>
<option value="Huissignies">Huissignies</option>
<option value="Huizingen">Huizingen</option>
<option value="Huldenberg">Huldenberg</option>
<option value="Hulshout">Hulshout</option>
<option value="Hulsonniaux">Hulsonniaux</option>
<option value="Hulste">Hulste</option>
<option value="Humain">Humain</option>
<option value="Humbeek">Humbeek</option>
<option value="Hundelgem">Hundelgem</option>
<option value="Huppaye">Huppaye</option>
<option value="Huy">Huy</option>
<option value="Hyon">Hyon</option>
<option value="Ichtegem">Ichtegem</option>
<option value="Iddergem">Iddergem</option>
<option value="Idegem">Idegem</option>
<option value="Ieper">Ieper</option>
<option value="Impe">Impe</option>
<option value="Incourt">Incourt</option>
<option value="Ingelmunster">Ingelmunster</option>
<option value="Ingooigem">Ingooigem</option>
<option value="Irchonwelz">Irchonwelz</option>
<option value="Isiéres">Isiéres</option>
<option value="Isnes">Isnes</option>
<option value="Itegem">Itegem</option>
<option value="Itterbeek">Itterbeek</option>
<option value="Ittre">Ittre</option>
<option value="Ivoz-Ramet">Ivoz-Ramet</option>
<option value="Izegem">Izegem</option>
<option value="Izel">Izel</option>
<option value="Izenberge">Izenberge</option>
<option value="Izier">Izier</option>
<option value="Jabbeke">Jabbeke</option>
<option value="Jalhay">Jalhay</option>
<option value="Jallet">Jallet</option>
<option value="Jamagne">Jamagne</option>
<option value="Jambes (Namur)">Jambes (Namur)</option>
<option value="Jamiolle">Jamiolle</option>
<option value="Jamioulx">Jamioulx</option>
<option value="Jamoigne">Jamoigne</option>
<option value="Jandrain-Jandrenouille">Jandrain-Jandrenouille</option>
<option value="Jauche">Jauche</option>
<option value="Jauchelette">Jauchelette</option>
<option value="Javingue">Javingue</option>
<option value="Jehay">Jehay</option>
<option value="Jehonville">Jehonville</option>
<option value="Jemappes">Jemappes</option>
<option value="Jemelle">Jemelle</option>
<option value="Jemeppe-sur-Meuse">Jemeppe-sur-Meuse</option>
<option value="Jemeppe-sur-Sambre">Jemeppe-sur-Sambre</option>
<option value="Jeneffe (Lg.)">Jeneffe (Lg.)</option>
<option value="Jeneffe (Nam.)">Jeneffe (Nam.)</option>
<option value="Jesseren">Jesseren</option>
<option value="Jette">Jette</option>
<option value="Jeuk">Jeuk</option>
<option value="Jodoigne">Jodoigne</option>
<option value="Jodoigne-Souveraine">Jodoigne-Souveraine</option>
<option value="Jollain-Merlin">Jollain-Merlin</option>
<option value="Joncret">Joncret</option>
<option value="Julémont">Julémont</option>
<option value="Jumet (Charleroi)">Jumet (Charleroi)</option>
<option value="Jupille-sur-Meuse">Jupille-sur-Meuse</option>
<option value="Juprelle">Juprelle</option>
<option value="Jurbise">Jurbise</option>
<option value="Juseret">Juseret</option>
<option value="Kaaskerke">Kaaskerke</option>
<option value="Kachtem">Kachtem</option>
<option value="Kaggevinne">Kaggevinne</option>
<option value="Kain (Tournai)">Kain (Tournai)</option>
<option value="Kalken">Kalken</option>
<option value="Kallo (Beveren-Waas)">Kallo (Beveren-Waas)</option>
<option value="Kallo (Kieldrecht)">Kallo (Kieldrecht)</option>
<option value="Kalmthout">Kalmthout</option>
<option value="Kampenhout">Kampenhout</option>
<option value="Kanegem">Kanegem</option>
<option value="Kanne">Kanne</option>
<option value="Kapellen (Antw.)">Kapellen (Antw.)</option>
<option value="Kapellen (Bt.)">Kapellen (Bt.)</option>
<option value="Kapelle-op-den-Bos">Kapelle-op-den-Bos</option>
<option value="Kaprijke">Kaprijke</option>
<option value="Kaster">Kaster</option>
<option value="Kasterlee">Kasterlee</option>
<option value="Kaulille">Kaulille</option>
<option value="Keerbergen">Keerbergen</option>
<option value="Keiem">Keiem</option>
<option value="Kelmis">Kelmis</option>
<option value="Kemexhe">Kemexhe</option>
<option value="Kemmel">Kemmel</option>
<option value="Kemzeke">Kemzeke</option>
<option value="Kerkhove">Kerkhove</option>
<option value="Kerkom">Kerkom</option>
<option value="Kerkom-bij-Sint-Truiden">Kerkom-bij-Sint-Truiden</option>
<option value="Kerksken">Kerksken</option>
<option value="Kermt">Kermt</option>
<option value="Kerniel">Kerniel</option>
<option value="Kersbeek-Miskom">Kersbeek-Miskom</option>
<option value="Kessel">Kessel</option>
<option value="Kessel-Lo">Kessel-Lo</option>
<option value="Kessenich">Kessenich</option>
<option value="Kester">Kester</option>
<option value="Kettenis">Kettenis</option>
<option value="Keumiée">Keumiée</option>
<option value="Kieldrecht (Beveren)">Kieldrecht (Beveren)</option>
<option value="Kinrooi">Kinrooi</option>
<option value="Kleine-Brogel">Kleine-Brogel</option>
<option value="Kleine-Spouwen">Kleine-Spouwen</option>
<option value="Klein-Gelmen">Klein-Gelmen</option>
<option value="Klemskerke">Klemskerke</option>
<option value="Klerken">Klerken</option>
<option value="Kluisbergen">Kluisbergen</option>
<option value="Kluizen">Kluizen</option>
<option value="Knesselare">Knesselare</option>
<option value="Knokke">Knokke</option>
<option value="Knokke-Heist">Knokke-Heist</option>
<option value="Kobbegem">Kobbegem</option>
<option value="Koekelare">Koekelare</option>
<option value="Koekelberg">Koekelberg</option>
<option value="Koersel">Koersel</option>
<option value="Koksijde">Koksijde</option>
<option value="Kolmont (Borgloon)">Kolmont (Borgloon)</option>
<option value="Kolmont (Tongeren)">Kolmont (Tongeren)</option>
<option value="Komen">Komen</option>
<option value="Komen-Waasten">Komen-Waasten</option>
<option value="Koningshooikt">Koningshooikt</option>
<option value="Koninksem">Koninksem</option>
<option value="Kontich">Kontich</option>
<option value="Kooigem">Kooigem</option>
<option value="Koolkerke">Koolkerke</option>
<option value="Koolskamp">Koolskamp</option>
<option value="Korbeek-Dijle">Korbeek-Dijle</option>
<option value="Korbeek-Lo">Korbeek-Lo</option>
<option value="Kortemark">Kortemark</option>
<option value="Kortenaken">Kortenaken</option>
<option value="Kortenberg">Kortenberg</option>
<option value="Kortessem">Kortessem</option>
<option value="Kortijs">Kortijs</option>
<option value="Kortrijk">Kortrijk</option>
<option value="Kozen">Kozen</option>
<option value="Kraainem">Kraainem</option>
<option value="Krombeke">Krombeke</option>
<option value="Kruibeke">Kruibeke</option>
<option value="Kruishoutem">Kruishoutem</option>
<option value="Kumtich">Kumtich</option>
<option value="Kuringen">Kuringen</option>
<option value="Kuttekoven">Kuttekoven</option>
<option value="Kuurne">Kuurne</option>
<option value="Kwaadmechelen">Kwaadmechelen</option>
<option value="Kwaremont">Kwaremont</option>
<option value="La Bouverie">La Bouverie</option>
<option value="La Calamine">La Calamine</option>
<option value="La Glanerie">La Glanerie</option>
<option value="La Gleize">La Gleize</option>
<option value="La Hestre">La Hestre</option>
<option value="La Hulpe">La Hulpe</option>
<option value="La Louviére">La Louviére</option>
<option value="La Reid">La Reid</option>
<option value="La Roche-en-Ardenne">La Roche-en-Ardenne</option>
<option value="Laar">Laar</option>
<option value="Laarne">Laarne</option>
<option value="Labuissiére">Labuissiére</option>
<option value="Lacuisine">Lacuisine</option>
<option value="Ladeuze">Ladeuze</option>
<option value="Laforêt">Laforêt</option>
<option value="Lahamaide">Lahamaide</option>
<option value="Laken (Brussel-stad)">Laken (Brussel-stad)</option>
<option value="Lamain">Lamain</option>
<option value="Lambermont">Lambermont</option>
<option value="Lambusart">Lambusart</option>
<option value="Lamine">Lamine</option>
<option value="Lamontzée">Lamontzée</option>
<option value="Lamorteau">Lamorteau</option>
<option value="Lampernisse">Lampernisse</option>
<option value="Lanaken">Lanaken</option>
<option value="Lanaye">Lanaye</option>
<option value="Landegem">Landegem</option>
<option value="Landelies">Landelies</option>
<option value="Landen">Landen</option>
<option value="Landenne">Landenne</option>
<option value="Landskouter">Landskouter</option>
<option value="Laneffe">Laneffe</option>
<option value="Langdorp">Langdorp</option>
<option value="Langemark">Langemark</option>
<option value="Langemark-Poelkapelle">Langemark-Poelkapelle</option>
<option value="Lanklaar">Lanklaar</option>
<option value="Lanquesaint">Lanquesaint</option>
<option value="Lantin">Lantin</option>
<option value="Lantremange">Lantremange</option>
<option value="Laplaigne">Laplaigne</option>
<option value="Lapscheure">Lapscheure</option>
<option value="Lasne">Lasne</option>
<option value="Lasne-Chapelle-St-Lambert">Lasne-Chapelle-St-Lambert</option>
<option value="Lathuy">Lathuy</option>
<option value="Latinne">Latinne</option>
<option value="Latour">Latour</option>
<option value="Lauw">Lauw</option>
<option value="Lauwe">Lauwe</option>
<option value="Lavacherie">Lavacherie</option>
<option value="Lavaux-Sainte-Anne">Lavaux-Sainte-Anne</option>
<option value="Lavoir">Lavoir</option>
<option value="Le Mesnil">Le Mesnil</option>
<option value="Le Roeulx">Le Roeulx</option>
<option value="Le Roux">Le Roux</option>
<option value="Lebbeke">Lebbeke</option>
<option value="L'Ecluse">L'Ecluse</option>
<option value="Lede">Lede</option>
<option value="Ledeberg (Gent)">Ledeberg (Gent)</option>
<option value="Ledegem">Ledegem</option>
<option value="Leefdaal">Leefdaal</option>
<option value="Leerbeek">Leerbeek</option>
<option value="Leernes">Leernes</option>
<option value="Leers-et-Fosteau">Leers-et-Fosteau</option>
<option value="Leers-Nord">Leers-Nord</option>
<option value="Leest">Leest</option>
<option value="Leeuwergem">Leeuwergem</option>
<option value="Leffinge">Leffinge</option>
<option value="Léglise">Léglise</option>
<option value="Leignon">Leignon</option>
<option value="Leisele">Leisele</option>
<option value="Leke">Leke</option>
<option value="Lembeek">Lembeek</option>
<option value="Lembeke">Lembeke</option>
<option value="Lemberge">Lemberge</option>
<option value="Lendelede">Lendelede</option>
<option value="Lennik">Lennik</option>
<option value="Lens">Lens</option>
<option value="Lens-Saint-Remy">Lens-Saint-Remy</option>
<option value="Lens-Saint-Servais">Lens-Saint-Servais</option>
<option value="Lens-sur-Geer">Lens-sur-Geer</option>
<option value="Leopoldsburg">Leopoldsburg</option>
<option value="Les Avins">Les Avins</option>
<option value="Les Bulles">Les Bulles</option>
<option value="Les Hayons">Les Hayons</option>
<option value="Les Waleffes">Les Waleffes</option>
<option value="L'Escaillére">L'Escaillére</option>
<option value="Lesdain">Lesdain</option>
<option value="Lessines">Lessines</option>
<option value="Lessive">Lessive</option>
<option value="Lesterny">Lesterny</option>
<option value="Lesve">Lesve</option>
<option value="Lettelingen">Lettelingen</option>
<option value="Letterhoutem">Letterhoutem</option>
<option value="Leugnies">Leugnies</option>
<option value="Leupegem">Leupegem</option>
<option value="Leut">Leut</option>
<option value="Leuven">Leuven</option>
<option value="Leuze (Nam.)">Leuze (Nam.)</option>
<option value="Leuze-en-Hainaut">Leuze-en-Hainaut</option>
<option value="Leval-Chaudeville">Leval-Chaudeville</option>
<option value="Leval-Trahegnies">Leval-Trahegnies</option>
<option value="Liberchies">Liberchies</option>
<option value="Libin">Libin</option>
<option value="Libramont-Chevigny">Libramont-Chevigny</option>
<option value="Lichtaart">Lichtaart</option>
<option value="Lichtervelde">Lichtervelde</option>
<option value="Liedekerke">Liedekerke</option>
<option value="Lieferinge">Lieferinge</option>
<option value="Liége 1">Liége 1</option>
<option value="Liége 2">Liége 2</option>
<option value="Lier">Lier</option>
<option value="Lierde">Lierde</option>
<option value="Lierneux">Lierneux</option>
<option value="Liernu">Liernu</option>
<option value="Liers">Liers</option>
<option value="Liezele">Liezele</option>
<option value="Ligne">Ligne</option>
<option value="Ligney">Ligney</option>
<option value="Ligny">Ligny</option>
<option value="Lille">Lille</option>
<option value="Lillo">Lillo</option>
<option value="Lillois-Witterzée">Lillois-Witterzée</option>
<option value="Limal">Limal</option>
<option value="Limbourg">Limbourg</option>
<option value="Limelette">Limelette</option>
<option value="Limerlé">Limerlé</option>
<option value="Limont">Limont</option>
<option value="Lincent">Lincent</option>
<option value="Linden">Linden</option>
<option value="Linkebeek">Linkebeek</option>
<option value="Linkhout">Linkhout</option>
<option value="Linsmeau">Linsmeau</option>
<option value="Lint">Lint</option>
<option value="Linter">Linter</option>
<option value="Lippelo">Lippelo</option>
<option value="Lisogne">Lisogne</option>
<option value="Lissewege">Lissewege</option>
<option value="Lives-sur-Meuse">Lives-sur-Meuse</option>
<option value="Lixhe">Lixhe</option>
<option value="Lo">Lo</option>
<option value="Lobbes">Lobbes</option>
<option value="Lochristi">Lochristi</option>
<option value="Lodelinsart">Lodelinsart</option>
<option value="Loenhout">Loenhout</option>
<option value="Loker">Loker</option>
<option value="Lokeren">Lokeren</option>
<option value="Loksbergen">Loksbergen</option>
<option value="Lombardsijde">Lombardsijde</option>
<option value="Lombise">Lombise</option>
<option value="Lommel">Lommel</option>
<option value="Lommersweiler">Lommersweiler</option>
<option value="Lompret">Lompret</option>
<option value="Lomprez">Lomprez</option>
<option value="Loncin">Loncin</option>
<option value="Londerzeel">Londerzeel</option>
<option value="Longchamps (Lux.)">Longchamps (Lux.)</option>
<option value="Longchamps (Nam.)">Longchamps (Nam.)</option>
<option value="Longlier">Longlier</option>
<option value="Longueville">Longueville</option>
<option value="Longvilly">Longvilly</option>
<option value="Lontzen">Lontzen</option>
<option value="Lonzée">Lonzée</option>
<option value="Loonbeek">Loonbeek</option>
<option value="Loppem">Loppem</option>
<option value="Lorcé">Lorcé</option>
<option value="Lo-Reninge">Lo-Reninge</option>
<option value="Lot">Lot</option>
<option value="Lotenhulle">Lotenhulle</option>
<option value="Louette-Saint-Denis">Louette-Saint-Denis</option>
<option value="Louette-Saint-Pierre">Louette-Saint-Pierre</option>
<option value="Loupoigne">Loupoigne</option>
<option value="Louvain-la-Neuve">Louvain-la-Neuve</option>
<option value="Louveigné (Aywaille)">Louveigné (Aywaille)</option>
<option value="Louveigné (Sprimont)">Louveigné (Sprimont)</option>
<option value="Lovendegem">Lovendegem</option>
<option value="Lovenjoel">Lovenjoel</option>
<option value="Loverval">Loverval</option>
<option value="Loyers">Loyers</option>
<option value="Lubbeek">Lubbeek</option>
<option value="Luingne">Luingne</option>
<option value="Lummen">Lummen</option>
<option value="Lustin">Lustin</option>
<option value="Luttre">Luttre</option>
<option value="Maarkedal">Maarkedal</option>
<option value="Maarke-Kerkem">Maarke-Kerkem</option>
<option value="Maaseik">Maaseik</option>
<option value="Maasmechelen">Maasmechelen</option>
<option value="Mabompré">Mabompré</option>
<option value="Machelen (Bt)">Machelen (Bt)</option>
<option value="Machelen (O.-Vl.)">Machelen (O.-Vl.)</option>
<option value="Macon">Macon</option>
<option value="Macquenoise">Macquenoise</option>
<option value="Maffe">Maffe</option>
<option value="Maffle">Maffle</option>
<option value="Magnée">Magnée</option>
<option value="Maillen">Maillen</option>
<option value="Mainvault">Mainvault</option>
<option value="Maisiéres">Maisiéres</option>
<option value="Maissin">Maissin</option>
<option value="Maizeret">Maizeret</option>
<option value="Mal">Mal</option>
<option value="Maldegem">Maldegem</option>
<option value="Malderen">Malderen</option>
<option value="Malempré">Malempré</option>
<option value="Maléves-Ste-Marie-Wastines>Maléves-Ste-Marie-Wastines</option>
<option value="Malle">Malle</option>
<option value="Malmédy">Malmédy</option>
<option value="Malonne">Malonne</option>
<option value="Malvoisin">Malvoisin</option>
<option value="Manage">Manage</option>
<option value="Manderfeld">Manderfeld</option>
<option value="Manhay">Manhay</option>
<option value="Mannekensvere">Mannekensvere</option>
<option value="Maransart">Maransart</option>
<option value="Marbais (Bt.)">Marbais (Bt.)</option>
<option value="Marbaix (Ht.)>"Marbaix (Ht.)</option>
<option value="Marche-en-Famenne">Marche-en-Famenne</option>
<option value="Marche-les-Dames">Marche-les-Dames</option>
<option value="Marche-lez-Ecaussinnes">Marche-lez-Ecaussinnes</option>
<option value="Marchienne-au-Pont">Marchienne-au-Pont</option>
<option value="Marchin">Marchin</option>
<option value="Marchipont">Marchipont</option>
<option value="Marchovelette">Marchovelette</option>
<option value="Marcinelle">Marcinelle</option>
<option value="Marcourt">Marcourt</option>
<option value="Marcq">Marcq</option>
<option value="Marenne">Marenne</option>
<option value="Mariakerke (Gent)">Mariakerke (Gent)</option>
<option value="Mariekerke (Bornem)">Mariekerke (Bornem)</option>
<option value="Mariembourg">Mariembourg</option>
<option value="Mark">Mark</option>
<option value="Marke (Kortrijk)">Marke (Kortrijk)</option>
<option value="Markegem">Markegem</option>
<option value="Marneffe">Marneffe</option>
<option value="Marquain">Marquain</option>
<option value="Martelange">Martelange</option>
<option value="Martenslinde">Martenslinde</option>
<option value="Martouzin-Neuville">Martouzin-Neuville</option>
<option value="Masbourg">Masbourg</option>
<option value="Masnuy-Saint-Jean (Mons)">Masnuy-Saint-Jean (Mons)</option>
<option value="Masnuy-Saint-Pierre">Masnuy-Saint-Pierre</option>
<option value="Masnuy-St-Jean (Jurbise)">Masnuy-St-Jean (Jurbise)</option>
<option value="Massemen">Massemen</option>
<option value="Massenhoven">Massenhoven</option>
<option value="Matagne-la-Grande">Matagne-la-Grande</option>
<option value="Matagne-la-Petite">Matagne-la-Petite</option>
<option value="Mater">Mater</option>
<option value="Maubray">Maubray</option>
<option value="Maulde">Maulde</option>
<option value="Maurage">Maurage</option>
<option value="Mazée">Mazée</option>
<option value="Mazenzele">Mazenzele</option>
<option value="Mazy">Mazy</option>
<option value="Méan">Méan</option>
<option value="Mechelen">Mechelen</option>
<option value="Mechelen-aan-de-Maas">Mechelen-aan-de-Maas</option>
<option value="Mechelen-Bovelingen">Mechelen-Bovelingen</option>
<option value="Meeffe">Meeffe</option>
<option value="Meensel-Kiezegem">Meensel-Kiezegem</option>
<option value="Meer">Meer</option>
<option value="Meerbeek">Meerbeek</option>
<option value="Meerbeke">Meerbeke</option>
<option value="Meerdonk">Meerdonk</option>
<option value="Meerhout">Meerhout</option>
<option value="Meerle">Meerle</option>
<option value="Meeswijk">Meeswijk</option>
<option value="Meetkerke">Meetkerke</option>
<option value="Meeuwen">Meeuwen</option>
<option value="Meeuwen-Gruitrode">Meeuwen-Gruitrode</option>
<option value="Mehaigne">Mehaigne</option>
<option value="Meigem">Meigem</option>
<option value="Meilegem">Meilegem</option>
<option value="Meise">Meise</option>
<option value="Meix-devant-Virton">Meix-devant-Virton</option>
<option value="Meix-le-Tige">Meix-le-Tige</option>
<option value="Melden">Melden</option>
<option value="Meldert (Bt.)">Meldert (Bt.)</option>
<option value="Meldert (Limb.)">Meldert (Limb.)</option>
<option value="Meldert (O.-Vl.)">Meldert (O.-Vl.)</option>
<option value="Melen">Melen</option>
<option value="Mélin">Mélin</option>
<option value="Melkwezer">Melkwezer</option>
<option value="Melle">Melle</option>
<option value="Melles">Melles</option>
<option value="Mellet">Mellet</option>
<option value="Mellier">Mellier</option>
<option value="Melsbroek">Melsbroek</option>
<option value="Melsele">Melsele</option>
<option value="Melsen">Melsen</option>
<option value="Membach">Membach</option>
<option value="Membre">Membre</option>
<option value="Membruggen">Membruggen</option>
<option value="Mendonk">Mendonk</option>
<option value="Menen">Menen</option>
<option value="Merbes-le-Château">Merbes-le-Château</option>
<option value="Merbes-Sainte-Marie">Merbes-Sainte-Marie</option>
<option value="Merchtem">Merchtem</option>
<option value="Merdorp">Merdorp</option>
<option value="Mere">Mere</option>
<option value="Merelbeke">Merelbeke</option>
<option value="Merendree">Merendree</option>
<option value="Merkem">Merkem</option>
<option value="Merksem (Antwerpen)">Merksem (Antwerpen)</option>
<option value="Merksplas">Merksplas</option>
<option value="Merlemont">Merlemont</option>
<option value="Mesen">Mesen</option>
<option value="Meslin-l'Evêque">Meslin-l'Evêque</option>
<option value="Mesnil-Eglise">Mesnil-Eglise</option>
<option value="Mesnil-Saint-Blaise">Mesnil-Saint-Blaise</option>
<option value="Mespelare">Mespelare</option>
<option value="Messancy">Messancy</option>
<option value="Messelbroek">Messelbroek</option>
<option value="Messines">Messines</option>
<option value="Mesvin">Mesvin</option>
<option value="Mettekoven">Mettekoven</option>
<option value="Mettet">Mettet</option>
<option value="Meulebeke">Meulebeke</option>
<option value="Meux">Meux</option>
<option value="Mévergnies-lez-Lens">Mévergnies-lez-Lens</option>
<option value="Meyrode">Meyrode</option>
<option value="Michelbeke">Michelbeke</option>
<option value="Micheroux">Micheroux</option>
<option value="Middelburg">Middelburg</option>
<option value="Middelkerke">Middelkerke</option>
<option value="Miécret">Miécret</option>
<option value="Mielen-boven-Aalst">Mielen-boven-Aalst</option>
<option value="Mignault">Mignault</option>
<option value="Millen">Millen</option>
<option value="Milmort">Milmort</option>
<option value="Minderhout">Minderhout</option>
<option value="Mirwart">Mirwart</option>
<option value="Modave">Modave</option>
<option value="Moelingen">Moelingen</option>
<option value="Moen">Moen</option>
<option value="Moerbeke">Moerbeke</option>
<option value="Moerbeke-Waas">Moerbeke-Waas</option>
<option value="Moere">Moere</option>
<option value="Moerkerke">Moerkerke</option>
<option value="Moerzeke">Moerzeke</option>
<option value="Moeskroen">Moeskroen</option>
<option value="Moha">Moha</option>
<option value="Mohiville">Mohiville</option>
<option value="Moignelée">Moignelée</option>
<option value="Moircy">Moircy</option>
<option value="Mol">Mol</option>
<option value="Molenbaix">Molenbaix</option>
<option value="Molenbeek-Wersbeek">Molenbeek-Wersbeek</option>
<option value="Molenbeersel">Molenbeersel</option>
<option value="Molenstede">Molenstede</option>
<option value="Mollem">Mollem</option>
<option value="Momalle">Momalle</option>
<option value="Momignies">Momignies</option>
<option value="Monceau-en-Ardenne">Monceau-en-Ardenne</option>
<option value="Monceau-Imbrechies">Monceau-Imbrechies</option>
<option value="Monceau-sur-Sambre">Monceau-sur-Sambre</option>
<option value="Mons">Mons</option>
<option value="Mons-lez-Liége">Mons-lez-Liége</option>
<option value="Monstreux">Monstreux</option>
<option value="Mont (Lux.)">Mont (Lux.)</option>
<option value="Mont (Nam.)">Mont (Nam.)</option>
<option value="Montbliart">Montbliart</option>
<option value="Mont-de-l'Enclus">Mont-de-l'Enclus</option>
<option value="Montegnée">Montegnée</option>
<option value="Montenaken">Montenaken</option>
<option value="Mont-Gauthier">Mont-Gauthier</option>
<option value="Montignies-lez-Lens">Montignies-lez-Lens</option>
<option value="Montignies-St-Christophe">Montignies-St-Christophe</option>
<option value="Montignies-sur-Roc">Montignies-sur-Roc</option>
<option value="Montignies-sur-Sambre">Montignies-sur-Sambre</option>
<option value="Montigny-le-Tilleul">Montigny-le-Tilleul</option>
<option value="Montleban">Montleban</option>
<option value="Montroeul-au-Bois">Montroeul-au-Bois</option>
<option value="Montroeul-sur-Haine">Montroeul-sur-Haine</option>
<option value="Mont-Saint-André">Mont-Saint-André</option>
<option value="Mont-Saint-Aubert">Mont-Saint-Aubert</option>
<option value="Mont-Sainte-Aldegonde">Mont-Sainte-Aldegonde</option>
<option value="Mont-Sainte-Geneviéve">Mont-Sainte-Geneviéve</option>
<option value="Mont-Saint-Guibert">Mont-Saint-Guibert</option>
<option value="Mont-sur-Marchienne">Mont-sur-Marchienne</option>
<option value="Montzen">Montzen</option>
<option value="Moorsel">Moorsel</option>
<option value="Moorsele">Moorsele</option>
<option value="Moorslede">Moorslede</option>
<option value="Moortsele">Moortsele</option>
<option value="Mopertingen">Mopertingen</option>
<option value="Moregem">Moregem</option>
<option value="Moresnet">Moresnet</option>
<option value="Morhet">Morhet</option>
<option value="Morialmé">Morialmé</option>
<option value="Morkhoven">Morkhoven</option>
<option value="Morlanwelz">Morlanwelz</option>
<option value="Morlanwelz-Mariemont">Morlanwelz-Mariemont</option>
<option value="Mormont">Mormont</option>
<option value="Mornimont">Mornimont</option>
<option value="Mortier">Mortier</option>
<option value="Mortroux">Mortroux</option>
<option value="Mortsel">Mortsel</option>
<option value="Morville">Morville</option>
<option value="Mouland">Mouland</option>
<option value="Moulbaix">Moulbaix</option>
<option value="Mourcourt">Mourcourt</option>
<option value="Mouscron">Mouscron</option>
<option value="Moustier (Ht.)">Moustier (Ht.)</option>
<option value="Moustier-sur-Sambre">Moustier-sur-Sambre</option>
<option value="Mouzaive">Mouzaive</option>
<option value="Moxhe">Moxhe</option>
<option value="Mozet">Mozet</option>
<option value="Muizen (Limb.)">Muizen (Limb.)</option>
<option value="Muizen (Mechelen)">Muizen (Mechelen)</option>
<option value="Mullem">Mullem</option>
<option value="Munkzwalm">Munkzwalm</option>
<option value="Muno">Muno</option>
<option value="Munsterbilzen">Munsterbilzen</option>
<option value="Munte">Munte</option>
<option value="Musson">Musson</option>
<option value="Mussy-la-Ville">Mussy-la-Ville</option>
<option value="My">My</option>
<option value="Naast">Naast</option>
<option value="Nadrin">Nadrin</option>
<option value="Nafraiture">Nafraiture</option>
<option value="Nalinnes">Nalinnes</option>
<option value="Namêche">Namêche</option>
<option value="Namur">Namur</option>
<option value="Nandrin">Nandrin</option>
<option value="Naninne">Naninne</option>
<option value="Naomé">Naomé</option>
<option value="Nassogne">Nassogne</option>
<option value="Natoye">Natoye</option>
<option value="Nazareth">Nazareth</option>
<option value="Néchin">Néchin</option>
<option value="Nederboelare">Nederboelare</option>
<option value="Nederbrakel">Nederbrakel</option>
<option value="Nederename">Nederename</option>
<option value="Nederhasselt">Nederhasselt</option>
<option value="Nederokkerzeel">Nederokkerzeel</option>
<option value="Neder-over-Heembeek">Neder-over-Heembeek</option>
<option value="Nederzwalm-Hermelgem">Nederzwalm-Hermelgem</option>
<option value="Neerglabbeek">Neerglabbeek</option>
<option value="Neerharen">Neerharen</option>
<option value="Neerhespen">Neerhespen</option>
<option value="Neerheylissem">Neerheylissem</option>
<option value="Neerijse">Neerijse</option>
<option value="Neerlanden">Neerlanden</option>
<option value="Neerlinter">Neerlinter</option>
<option value="Neeroeteren">Neeroeteren</option>
<option value="Neerpelt">Neerpelt</option>
<option value="Neerrepen">Neerrepen</option>
<option value="Neervelp">Neervelp</option>
<option value="Neerwaasten">Neerwaasten</option>
<option value="Neerwinden">Neerwinden</option>
<option value="Neigem">Neigem</option>
<option value="Nerem">Nerem</option>
<option value="Nessonvaux">Nessonvaux</option>
<option value="Nethen">Nethen</option>
<option value="Nettinne">Nettinne</option>
<option value="Neufchâteau">Neufchâteau</option>
<option value="Neufchâteau (Lg.)">Neufchâteau (Lg.)</option>
<option value="Neufmaison">Neufmaison</option>
<option value="Neufvilles">Neufvilles</option>
<option value="Neu-Moresnet">Neu-Moresnet</option>
<option value="Neupré">Neupré</option>
<option value="Neuville (Philippeville)">Neuville (Philippeville)</option>
<option value="Neuville-en-Condroz">Neuville-en-Condroz</option>
<option value="Nevele">Nevele</option>
<option value="Niel">Niel</option>
<option value="Niel-bij-As">Niel-bij-As</option>
<option value="Niel-bij-Sint-Truiden">Niel-bij-Sint-Truiden</option>
<option value="Nieuwenhove">Nieuwenhove</option>
<option value="Nieuwenrode">Nieuwenrode</option>
<option value="Nieuwerkerken (Aalst)">Nieuwerkerken (Aalst)</option>
<option value="Nieuwerkerken (Limb.)">Nieuwerkerken (Limb.)</option>
<option value="Nieuwkapelle">Nieuwkapelle</option>
<option value="Nieuwkerke">Nieuwkerke</option>
<option value="Nieuwkerken-Waas">Nieuwkerken-Waas</option>
<option value="Nieuwmunster">Nieuwmunster</option>
<option value="Nieuwpoort">Nieuwpoort</option>
<option value="Nieuwrode">Nieuwrode</option>
<option value="Nijlen">Nijlen</option>
<option value="Nil-St-Vincent-St-Martin">Nil-St-Vincent-St-Martin</option>
<option value="Nimy (Mons)">Nimy (Mons)</option>
<option value="Ninove">Ninove</option>
<option value="Nismes">Nismes</option>
<option value="Nivelles">Nivelles</option>
<option value="Niverlée">Niverlée</option>
<option value="Nives">Nives</option>
<option value="Nobressart">Nobressart</option>
<option value="Nodebais">Nodebais</option>
<option value="Noduwez">Noduwez</option>
<option value="Noirchain">Noirchain</option>
<option value="Noirefontaine">Noirefontaine</option>
<option value="Noiseux">Noiseux</option>
<option value="Nokere">Nokere</option>
<option value="Nollevaux">Nollevaux</option>
<option value="Noorderwijk">Noorderwijk</option>
<option value="Noordschote">Noordschote</option>
<option value="Nossegem">Nossegem</option>
<option value="Nothomb">Nothomb</option>
<option value="Nouvelles">Nouvelles</option>
<option value="Noville (Lg.)">Noville (Lg.)</option>
<option value="Noville (Lux.)">Noville (Lux.)</option>
<option value="Noville-les-Bois">Noville-les-Bois</option>
<option value="Noville-sur-Méhaigne">Noville-sur-Méhaigne</option>
<option value="Nukerke">Nukerke</option>
<option value="Obaix">Obaix</option>
<option value="Obigies">Obigies</option>
<option value="Obourg">Obourg</option>
<option value="Ochamps">Ochamps</option>
<option value="Ocquier">Ocquier</option>
<option value="Odeigne">Odeigne</option>
<option value="Odeur">Odeur</option>
<option value="Oedelem">Oedelem</option>
<option value="Oekene">Oekene</option>
<option value="Oelegem">Oelegem</option>
<option value="Oeren">Oeren</option>
<option value="Oeselgem">Oeselgem</option>
<option value="Oetingen">Oetingen</option>
<option value="Oeudeghien">Oeudeghien</option>
<option value="Oevel">Oevel</option>
<option value="Offagne">Offagne</option>
<option value="Ogy">Ogy</option>
<option value="Ohain">Ohain</option>
<option value="Ohey">Ohey</option>
<option value="Oignies-en-Thiérache">Oignies-en-Thiérache</option>
<option value="Oisquercq">Oisquercq</option>
<option value="Oizy">Oizy</option>
<option value="Okegem">Okegem</option>
<option value="Olen">Olen</option>
<option value="Oleye">Oleye</option>
<option value="Ollignies">Ollignies</option>
<option value="Olloy-sur-Viroin">Olloy-sur-Viroin</option>
<option value="Olmen">Olmen</option>
<option value="Olne">Olne</option>
<option value="Olsene">Olsene</option>
<option value="Omal">Omal</option>
<option value="Ombret">Ombret</option>
<option value="Omezée">Omezée</option>
<option value="On">On</option>
<option value="Onhaye">Onhaye</option>
<option value="Onkerzele">Onkerzele</option>
<option value="Onnezies">Onnezies</option>
<option value="Onoz">Onoz</option>
<option value="Onze-Lieve-Vrouw-Lombeek">Onze-Lieve-Vrouw-Lombeek</option>
<option value="Onze-Lieve-Vrouw-Waver">Onze-Lieve-Vrouw-Waver</option>
<option value="Ooigem">Ooigem</option>
<option value="Ooike (Oudenaarde)">Ooike (Oudenaarde)</option>
<option value="Ooike (Wortegem-Petegem)">Ooike (Wortegem-Petegem)</option>
<option value="Oomb.(St-Lievens-Houtem)">Oomb.(St-Lievens-Houtem)</option>
<option value="Oombergen (Zottegem)">Oombergen (Zottegem)</option>
<option value="Oorbeek">Oorbeek</option>
<option value="Oordegem">Oordegem</option>
<option value="Oostakker">Oostakker</option>
<option value="Oostduinkerke">Oostduinkerke</option>
<option value="Oosteeklo">Oosteeklo</option>
<option value="Oostende">Oostende</option>
<option value="Oosterzele">Oosterzele</option>
<option value="Oostham">Oostham</option>
<option value="Oostkamp">Oostkamp</option>
<option value="Oostkerke (Damme)">Oostkerke (Damme)</option>
<option value="Oostkerke (Diksmuide)">Oostkerke (Diksmuide)</option>
<option value="Oostmalle">Oostmalle</option>
<option value="Oostnieuwkerke">Oostnieuwkerke</option>
<option value="Oostrozebeke">Oostrozebeke</option>
<option value="Oostvleteren">Oostvleteren</option>
<option value="Oostwinkel">Oostwinkel</option>
<option value="Opbrakel">Opbrakel</option>
<option value="Opdorp">Opdorp</option>
<option value="Opglabbeek">Opglabbeek</option>
<option value="Opgrimbie">Opgrimbie</option>
<option value="Ophain-Bois-Seigneur-Isaac">Ophain-Bois-Seigneur-Isaac</option>
<option value="Ophasselt">Ophasselt</option>
<option value="Opheers">Opheers</option>
<option value="Opheylissem">Opheylissem</option>
<option value="Ophoven">Ophoven</option>
<option value="Opitter">Opitter</option>
<option value="Oplinter">Oplinter</option>
<option value="Opoeteren">Opoeteren</option>
<option value="Opont">Opont</option>
<option value="Opprebais">Opprebais</option>
<option value="Oppuurs">Oppuurs</option>
<option value="Opvelp">Opvelp</option>
<option value="Opwijk">Opwijk</option>
<option value="Orbais">Orbais</option>
<option value="Orchimont">Orchimont</option>
<option value="Orcq">Orcq</option>
<option value="Ordingen">Ordingen</option>
<option value="Oret">Oret</option>
<option value="Oreye">Oreye</option>
<option value="Orgeo">Orgeo</option>
<option value="Ormeignies">Ormeignies</option>
<option value="Orp-Jauche">Orp-Jauche</option>
<option value="Orp-le-Grand">Orp-le-Grand</option>
<option value="Orroir">Orroir</option>
<option value="Orsmaal-Gussenhoven">Orsmaal-Gussenhoven</option>
<option value="Ortho">Ortho</option>
<option value="Ostiches">Ostiches</option>
<option value="Otegem">Otegem</option>
<option value="Oteppe">Oteppe</option>
<option value="Othée">Othée</option>
<option value="Otrange">Otrange</option>
<option value="Ottenburg">Ottenburg</option>
<option value="Ottergem">Ottergem</option>
<option value="Ottignies">Ottignies</option>
<option value="Oudegem">Oudegem</option>
<option value="Oudekapelle">Oudekapelle</option>
<option value="Oudenaarde">Oudenaarde</option>
<option value="Oudenaken">Oudenaken</option>
<option value="Oudenburg">Oudenburg</option>
<option value="Oudergem">Oudergem</option>
<option value="Oud-Heverlee">Oud-Heverlee</option>
<option value="Oud-Turnhout">Oud-Turnhout</option>
<option value="Ouffet">Ouffet</option>
<option value="Ougrée">Ougrée</option>
<option value="Oupeye">Oupeye</option>
<option value="Outer">Outer</option>
<option value="Outgaarden">Outgaarden</option>
<option value="Outrelouxhe">Outrelouxhe</option>
<option value="Outrijve">Outrijve</option>
<option value="Ouwegem">Ouwegem</option>
<option value="Overboelare">Overboelare</option>
<option value="Overhespen">Overhespen</option>
<option value="Overijse">Overijse</option>
<option value="Overmere">Overmere</option>
<option value="Overpelt">Overpelt</option>
<option value="Overrepen">Overrepen</option>
<option value="Overwinden">Overwinden</option>
<option value="Paal">Paal</option>
<option value="Paifve">Paifve</option>
<option value="Pailhe">Pailhe</option>
<option value="Paliseul">Paliseul</option>
<option value="Pamel">Pamel</option>
<option value="Papignies">Papignies</option>
<option value="Parike">Parike</option>
<option value="Passendale">Passendale</option>
<option value="Patignies">Patignies</option>
<option value="Pâturages">Pâturages</option>
<option value="Paulatem">Paulatem</option>
<option value="Pecq">Pecq</option>
<option value="Peer">Peer</option>
<option value="Peissant">Peissant</option>
<option value="Pellaines">Pellaines</option>
<option value="Pellenberg">Pellenberg</option>
<option value="Pepingen">Pepingen</option>
<option value="Pepinster">Pepinster</option>
<option value="Perk">Perk</option>
<option value="Péronnes-lez-Antoing">Péronnes-lez-Antoing</option>
<option value="Péronnes-lez-Binche">Péronnes-lez-Binche</option>
<option value="Péruwelz">Péruwelz</option>
<option value="Pervijze">Pervijze</option>
<option value="Perwez">Perwez</option>
<option value="Perwez-Haillot">Perwez-Haillot</option>
<option value="Pesche">Pesche</option>
<option value="Pessoux">Pessoux</option>
<option value="Petegem-aan-de-Leie">Petegem-aan-de-Leie</option>
<option value="Petegem-aan-de-Schelde">Petegem-aan-de-Schelde</option>
<option value="Petigny">Petigny</option>
<option value="Petite-Chapelle">Petite-Chapelle</option>
<option value="Petit-Enghien">Petit-Enghien</option>
<option value="Petit-Fays">Petit-Fays</option>
<option value="Petit-Hallet">Petit-Hallet</option>
<option value="Petit-Rechain">Petit-Rechain</option>
<option value="Petit-Roeulx-lez-Braine">Petit-Roeulx-lez-Braine</option>
<option value="Petit-Roeulx-lez-Nivelles">Petit-Roeulx-lez-Nivelles</option>
<option value="Petit-Thier">Petit-Thier</option>
<option value="Peutie">Peutie</option>
<option value="Philippeville">Philippeville</option>
<option value="Piéton">Piéton</option>
<option value="Piétrain">Piétrain</option>
<option value="Piétrebais">Piétrebais</option>
<option value="Pipaix">Pipaix</option>
<option value="Piringen">Piringen</option>
<option value="Pironchamps">Pironchamps</option>
<option value="Pittem">Pittem</option>
<option value="Plainevaux">Plainevaux</option>
<option value="Plancenoit">Plancenoit</option>
<option value="Ploegsteert">Ploegsteert</option>
<option value="Plombiéres">Plombiéres</option>
<option value="Poederlee">Poederlee</option>
<option value="Poeke">Poeke</option>
<option value="Poelkapelle">Poelkapelle</option>
<option value="Poesele">Poesele</option>
<option value="Pollare">Pollare</option>
<option value="Polleur (Theux)">Polleur (Theux)</option>
<option value="Polleur (Verviers)">Polleur (Verviers)</option>
<option value="Pollinkhove">Pollinkhove</option>
<option value="Pommeroeul">Pommeroeul</option>
<option value="Pondr"me">Pondr"me</option>
<option value="Pont-...-Celles">Pont-...-Celles</option>
<option value="Pont-de-Loup">Pont-de-Loup</option>
<option value="Pontillas">Pontillas</option>
<option value="Poperinge">Poperinge</option>
<option value="Poppel">Poppel</option>
<option value="Popuelles">Popuelles</option>
<option value="Porcheresse (Lux.)">Porcheresse (Lux.)</option>
<option value="Porcheresse (Nam.)">Porcheresse (Nam.)</option>
<option value="Pottes">Pottes</option>
<option value="Poucet">Poucet</option>
<option value="Poulseur">Poulseur</option>
<option value="Poupehan">Poupehan</option>
<option value="Pousset">Pousset</option>
<option value="Presgaux">Presgaux</option>
<option value="Presles">Presles</option>
<option value="Profondeville">Profondeville</option>
<option value="Proven">Proven</option>
<option value="Pry">Pry</option>
<option value="Pulderbos">Pulderbos</option>
<option value="Pulle">Pulle</option>
<option value="Purnode">Purnode</option>
<option value="Pussemange">Pussemange</option>
<option value="Putte">Putte</option>
<option value="Puurs">Puurs</option>
<option value="Quaregnon">Quaregnon</option>
<option value="Quartes">Quartes</option>
<option value="Quenast">Quenast</option>
<option value="Queue-du-Bois">Queue-du-Bois</option>
<option value="Quevaucamps">Quevaucamps</option>
<option value="Quévy-le-Grand">Quévy-le-Grand</option>
<option value="Quévy-le-Petit">Quévy-le-Petit</option>
<option value="Quiévrain">Quiévrain</option>
<option value="Rachecourt">Rachecourt</option>
<option value="Racour">Racour</option>
<option value="Raeren">Raeren</option>
<option value="Ragnies">Ragnies</option>
<option value="Rahier">Rahier</option>
<option value="Ramegnies">Ramegnies</option>
<option value="Ramegnies-Chin">Ramegnies-Chin</option>
<option value="Ramelot">Ramelot</option>
<option value="Ramillies">Ramillies</option>
<option value="Ramsdonk">Ramsdonk</option>
<option value="Ramsel">Ramsel</option>
<option value="Ramskapelle (Knokke-Heist)">Ramskapelle (Knokke-Heist)</option>
<option value="Ramskapelle (Nieuwpoort)">Ramskapelle (Nieuwpoort)</option>
<option value="Rance">Rance</option>
<option value="Ransart">Ransart</option>
<option value="Ransberg">Ransberg</option>
<option value="Ranst">Ranst</option>
<option value="Ravels">Ravels</option>
<option value="Rebaix">Rebaix</option>
<option value="Rebecq">Rebecq</option>
<option value="Rebecq-Rognon">Rebecq-Rognon</option>
<option value="Recht">Recht</option>
<option value="Recogne">Recogne</option>
<option value="Redu">Redu</option>
<option value="Reet">Reet</option>
<option value="Rekem">Rekem</option>
<option value="Rekkem">Rekkem</option>
<option value="Relegem">Relegem</option>
<option value="Remagne">Remagne</option>
<option value="Remersdaal">Remersdaal</option>
<option value="Remicourt">Remicourt</option>
<option value="Renaix">Renaix</option>
<option value="Rendeux">Rendeux</option>
<option value="Reninge">Reninge</option>
<option value="Reningelst">Reningelst</option>
<option value="Renlies">Renlies</option>
<option value="Reppel">Reppel</option>
<option value="Ressaix">Ressaix</option>
<option value="Ressegem">Ressegem</option>
<option value="Resteigne">Resteigne</option>
<option value="Retie">Retie</option>
<option value="Retinne">Retinne</option>
<option value="Reuland">Reuland</option>
<option value="Réves">Réves</option>
<option value="Rhisnes">Rhisnes</option>
<option value="Richelle">Richelle</option>
<option value="Riemst">Riemst</option>
<option value="Rienne">Rienne</option>
<option value="Riézes">Riézes</option>
<option value="Rijkel">Rijkel</option>
<option value="Rijkevorsel">Rijkevorsel</option>
<option value="Rijkhoven">Rijkhoven</option>
<option value="Rijmenam">Rijmenam</option>
<option value="Riksingen">Riksingen</option>
<option value="Rillaar">Rillaar</option>
<option value="Riviére">Riviére</option>
<option value="Rixensart">Rixensart</option>
<option value="Robechies">Robechies</option>
<option value="Robelmont">Robelmont</option>
<option value="Robertville">Robertville</option>
<option value="Roborst">Roborst</option>
<option value="Rochefort">Rochefort</option>
<option value="Rochehaut">Rochehaut</option>
<option value="Rocherath">Rocherath</option>
<option value="Roclenge-sur-Geer">Roclenge-sur-Geer</option>
<option value="Rocourt">Rocourt</option>
<option value="Roesbrugge-Haringe">Roesbrugge-Haringe</option>
<option value="Roeselare">Roeselare</option>
<option value="Rognée">Rognée</option>
<option value="Roisin">Roisin</option>
<option value="Roksem">Roksem</option>
<option value="Rollegem">Rollegem</option>
<option value="Rollegem-Kapelle">Rollegem-Kapelle</option>
<option value="Roloux">Roloux</option>
<option value="Roly">Roly</option>
<option value="Romedenne">Romedenne</option>
<option value="Romerée">Romerée</option>
<option value="Romershoven">Romershoven</option>
<option value="Romsée">Romsée</option>
<option value="Rongy">Rongy</option>
<option value="Ronquiéres">Ronquiéres</option>
<option value="Ronse">Ronse</option>
<option value="Ronsele">Ronsele</option>
<option value="Roosbeek">Roosbeek</option>
<option value="Roosdaal">Roosdaal</option>
<option value="Rosée">Rosée</option>
<option value="Roselies">Roselies</option>
<option value="Rosiéres">Rosiéres</option>
<option value="Rosmeer">Rosmeer</option>
<option value="Rosoux-Crenwick">Rosoux-Crenwick</option>
<option value="Rossignol">Rossignol</option>
<option value="Rotem">Rotem</option>
<option value="Rotheux-Rimiére">Rotheux-Rimiére</option>
<option value="Rotselaar">Rotselaar</option>
<option value="Roucourt">Roucourt</option>
<option value="Rouveroy (Ht.)">Rouveroy (Ht.)</option>
<option value="Rouvreux">Rouvreux</option>
<option value="Rouvroy">Rouvroy</option>
<option value="Roux">Roux</option>
<option value="Roux-Miroir">Roux-Miroir</option>
<option value="Roy">Roy</option>
<option value="Rozebeke">Rozebeke</option>
<option value="Ruddervoorde">Ruddervoorde</option>
<option value="Ruette">Ruette</option>
<option value="Ruien">Ruien</option>
<option value="Ruisbroek (Antw.)">Ruisbroek (Antw.)</option>
<option value="Ruisbroek (Bt.)">Ruisbroek (Bt.)</option>
<option value="Ruiselede">Ruiselede</option>
<option value="Rukkelingen-Loon">Rukkelingen-Loon</option>
<option value="Rulles">Rulles</option>
<option value="Rumbeke">Rumbeke</option>
<option value="Rumes">Rumes</option>
<option value="Rumillies">Rumillies</option>
<option value="Rummen">Rummen</option>
<option value="Rumsdorp">Rumsdorp</option>
<option value="Rumst">Rumst</option>
<option value="Runkelen">Runkelen</option>
<option value="Rupelmonde">Rupelmonde</option>
<option value="Russeignies">Russeignies</option>
<option value="Rutten">Rutten</option>
<option value="'s Gravenvoeren">'s Gravenvoeren</option>
<option value="'s Gravenwezel">'s Gravenwezel</option>
<option value="'s Herenelderen">'s Herenelderen</option>
<option value="Saint-Amand">Saint-Amand</option>
<option value="Saint-André">Saint-André</option>
<option value="Saint-Aubin">Saint-Aubin</option>
<option value="Saint-Denis (Ht.)">Saint-Denis (Ht.)</option>
<option value="Saint-Denis-Bovesse">Saint-Denis-Bovesse</option>
<option value="ainte-Cécile">Sainte-Cécile</option>
<option value="Sainte-Marie-Chevigny">Sainte-Marie-Chevigny</option>
<option value="Sainte-Marie-sur-Semois">Sainte-Marie-sur-Semois</option>
<option value="Sainte-Ode">Sainte-Ode</option>
<option value="Saintes">Saintes</option>
<option value="Saint-Georges-sur-Meuse">Saint-Georges-sur-Meuse</option>
<option value="Saint-Gérard">Saint-Gérard</option>
<option value="Saint-Germain">Saint-Germain</option>
<option value="Saint-Géry">Saint-Géry</option>
<option value="Saint-Ghislain">Saint-Ghislain</option>
<option value="Saint-Hubert">Saint-Hubert</option>
<option value="Saint-Jean-Geest">Saint-Jean-Geest</option>
<option value="Saint-Léger (Ht.)">Saint-Léger (Ht.)</option>
<option value="Saint-Léger (Lux.)">Saint-Léger (Lux.)</option>
<option value="Saint-Marc">Saint-Marc</option>
<option value="Saint-Mard">Saint-Mard</option>
<option value="Saint-Martin">Saint-Martin</option>
<option value="Saint-Maur">Saint-Maur</option>
<option value="Saint-Médard">Saint-Médard</option>
<option value="Saint-Nicolas (Lg.)">Saint-Nicolas (Lg.)</option>
<option value="Saint-Pierre">Saint-Pierre</option>
<option value="Saint-Remy (Ht.)">Saint-Remy (Ht.)</option>
<option value="Saint-Remy (Lg.)">Saint-Remy (Lg.)</option>
<option value="Saint-Remy-Geest">Saint-Remy-Geest</option>
<option value="Saint-Sauveur">Saint-Sauveur</option>
<option value="Saint-Servais">Saint-Servais</option>
<option value="Saint-Séverin">Saint-Séverin</option>
<option value="Saint-Symphorien">Saint-Symphorien</option>
<option value="Saint-Vaast">Saint-Vaast</option>
<option value="Saint-Vincent">Saint-Vincent</option>
<option value="Saint-Vith">Saint-Vith</option>
<option value="Saive">Saive</option>
<option value="Salles">Salles</option>
<option value="Samart">Samart</option>
<option value="Sambreville">Sambreville</option>
<option value="Samrée">Samrée</option>
<option value="Sankt Vith">Sankt Vith</option>
<option value="Sars-la-Bruyére">Sars-la-Bruyére</option>
<option value="Sars-la-Buissiére">Sars-la-Buissiére</option>
<option value="Sart-Bernard">Sart-Bernard</option>
<option value="Sart-Custinne">Sart-Custinne</option>
<option value="Sart-Dames-Avelines">Sart-Dames-Avelines</option>
<option value="Sart-en-Fagne">Sart-en-Fagne</option>
<option value="Sart-Eustache">Sart-Eustache</option>
<option value="Sart-lez-Spa">Sart-lez-Spa</option>
<option value="Sart-Saint-Laurent">Sart-Saint-Laurent</option>
<option value="Sautin">Sautin</option>
<option value="Sautour">Sautour</option>
<option value="Sauveniére">Sauveniére</option>
<option value="Schaarbeek">Schaarbeek</option>
<option value="Schaffen">Schaffen</option>
<option value="Schalkhoven">Schalkhoven</option>
<option value="Schaltin">Schaltin</option>
<option value="Schelderode">Schelderode</option>
<option value="Scheldewindeke">Scheldewindeke</option>
<option value="Schelle">Schelle</option>
<option value="Schellebelle">Schellebelle</option>
<option value="Schendelbeke">Schendelbeke</option>
<option value="Schepdaal">Schepdaal</option>
<option value="Scherpenheuvel">Scherpenheuvel</option>
<option value="Schilde">Schilde</option>
<option value="Schoenberg">Schoenberg</option>
<option value="Schönberg">Schönberg</option>
<option value="Schoonaarde">Schoonaarde</option>
<option value="Schore">Schore</option>
<option value="Schorisse">Schorisse</option>
<option value="Schoten">Schoten</option>
<option value="Schriek">Schriek</option>
<option value="Schuiferskapelle">Schuiferskapelle</option>
<option value="Schulen">Schulen</option>
<option value="Sclayn">Sclayn</option>
<option value="Scy">Scy</option>
<option value="Seilles">Seilles</option>
<option value="Sélange">Sélange</option>
<option value="Seloignes">Seloignes</option>
<option value="Semmerzake">Semmerzake</option>
<option value="Seneffe">Seneffe</option>
<option value="Sensenruth">Sensenruth</option>
<option value="Seny">Seny</option>
<option value="Senzeille">Senzeille</option>
<option value="Septon">Septon</option>
<option value="Seraing">Seraing</option>
<option value="Seraing-le-Château">Seraing-le-Château</option>
<option value="Serinchamps">Serinchamps</option>
<option value="Serskamp">Serskamp</option>
<option value="Serville">Serville</option>
<option value="Sibret">Sibret</option>
<option value="Signeulx">Signeulx</option>
<option value="Sijsele">Sijsele</option>
<option value="Silenrieux">Silenrieux</option>
<option value="Silly">Silly</option>
<option value="Sinaai-Waas">Sinaai-Waas</option>
<option value="Sinsin">Sinsin</option>
<option value="Sint-Agatha-Berchem">Sint-Agatha-Berchem</option>
<option value="Sint-Agatha-Rode">Sint-Agatha-Rode</option>
<option value="Sint-Amands">Sint-Amands</option>
<option value="Sint-Amandsberg">Sint-Amandsberg</option>
<option value="Sint-Andries">Sint-Andries</option>
<option value="Sint-Antelinks">Sint-Antelinks</option>
<option value="Sint-Baafs-Vijve">Sint-Baafs-Vijve</option>
<option value="Sint-Blasius-Boekel">Sint-Blasius-Boekel</option>
<option value="Sint-Denijs">Sint-Denijs</option>
<option value="Sint-Denijs-Boekel">Sint-Denijs-Boekel</option>
<option value="Sint-Denijs-Westrem">Sint-Denijs-Westrem</option>
<option value="Sint-Eloois-Vijve">Sint-Eloois-Vijve</option>
<option value="Sint-Eloois-Winkel">Sint-Eloois-Winkel</option>
<option value="Sint-Genesius-Rode">Sint-Genesius-Rode</option>
<option value="Sint-Gillis">Sint-Gillis</option>
<option value="Sint-Gillis-bij-Dendermonde">Sint-Gillis-bij-Dendermonde</option>
<option value="Sint-Gillis-Waas">Sint-Gillis-Waas</option>
<option value="Sint-Goriks-Oudenhove">Sint-Goriks-Oudenhove</option>
<option value="Sint-Huibrechts-Hern">Sint-Huibrechts-Hern</option>
<option value="Sint-Huibrechts-Lille">Sint-Huibrechts-Lille</option>
<option value="Sint-Jacobs-Kapelle">Sint-Jacobs-Kapelle</option>
<option value="Sint-Jan">Sint-Jan</option>
<option value="Sint-Jan-in-Eremo">Sint-Jan-in-Eremo</option>
<option value="Sint-Jans-Molenbeek">Sint-Jans-Molenbeek</option>
<option value="Sint-Job-in-'t-Goor">Sint-Job-in-'t-Goor</option>
<option value="Sint-Joost-ten-Node">Sint-Joost-ten-Node</option>
<option value="Sint-Joris (Beernem)">Sint-Joris (Beernem)</option>
<option value="Sint-Joris (Nieuwpoort)">Sint-Joris (Nieuwpoort)</option>
<option value="Sint-Joris-Weert">Sint-Joris-Weert</option>
<option value="Sint-Joris-Winge">Sint-Joris-Winge</option>
<option value="Sint-Katelijne-Waver">Sint-Katelijne-Waver</option>
<option value="Sint-Katherina-lombeek">Sint-Katherina-lombeek</option>
<option value="Sint-Kornelis-Horebeke">Sint-Kornelis-Horebeke</option>
<option value="Sint-Kruis (Brugge)">Sint-Kruis (Brugge)</option>
<option value="Sint-Kruis-Winkel">Sint-Kruis-Winkel</option>
<option value="Sint-Kwintens-Lennik">Sint-Kwintens-Lennik</option>
<option value="Sint-Lambrechts-Herk">Sint-Lambrechts-Herk</option>
<option value="Sint-Lambrechts-Woluwe">Sint-Lambrechts-Woluwe</option>
<option value="Sint-Laureins">Sint-Laureins</option>
<option value="Sint-Laureins-Berchem">Sint-Laureins-Berchem</option>
<option value="Sint-Lenaerts">Sint-Lenaerts</option>
<option value="Sint-Lievens-Esse">Sint-Lievens-Esse</option>
<option value="Sint-Lievens-Houtem">Sint-Lievens-Houtem</option>
<option value="Sint-Margriete">Sint-Margriete</option>
<option value="Sint-Margriete (Kortenaken)">Sint-Margriete (Kortenaken)</option>
<option value="Sint-Margriete-Houtem(Tien.)">Sint-Margriete-Houtem(Tien.)</option>
<option value="Sint-Maria-Horebeke">Sint-Maria-Horebeke</option>
<option value="Sint-Maria-Latem">Sint-Maria-Latem</option>
<option value="Sint-Maria-Lierde">Sint-Maria-Lierde</option>
<option value="Sint-Martens-Bodegem">Sint-Martens-Bodegem</option>
<option value="Sint-Martens-Latem">Sint-Martens-Latem</option>
<option value="Sint-Martens-Leerne">Sint-Martens-Leerne</option>
<option value="Sint-Martens-Lennik">Sint-Martens-Lennik</option>
<option value="Sint-Martens-Lierde">Sint-Martens-Lierde</option>
<option value="Sint-Martens-Voeren">Sint-Martens-Voeren</option>
<option value="Sint-Michiels">Sint-Michiels</option>
<option value="Sint-Niklaas">Sint-Niklaas</option>
<option value="Sint-Pauwels">Sint-Pauwels</option>
<option value="Sint-Pieters-Kapelle (Bt.)">Sint-Pieters-Kapelle (Bt.)</option>
<option value="Sint-Pieters-Kapelle(W.-Vl.)">Sint-Pieters-Kapelle(W.-Vl.)</option>
<option value="Sint-Pieters-Leeuw">Sint-Pieters-Leeuw</option>
<option value="Sint-Pieters-Rode">Sint-Pieters-Rode</option>
<option value="Sint-Pieters-Voeren">Sint-Pieters-Voeren</option>
<option value="Sint-Pieters-Woluwe">Sint-Pieters-Woluwe</option>
<option value="Sint-Rijkers">Sint-Rijkers</option>
<option value="Sint-Stevens-Woluwe">Sint-Stevens-Woluwe</option>
<option value="Sint-Truiden">Sint-Truiden</option>
<option value="Sint-Ulriks-Kapelle">Sint-Ulriks-Kapelle</option>
<option value="Sint-Maria-Oudenhove(Brakel)">Sint-Maria-Oudenhove(Brakel)</option>
<option value="Sint-Maria-Oudenhove(Zott.)">Sint-Maria-Oudenhove(Zott.)</option>
<option value="Sippenaeken">Sippenaeken</option>
<option value="Sirault">Sirault</option>
<option value="Sivry">Sivry</option>
<option value="Sivry-Rance">Sivry-Rance</option>
<option value="Sleidinge">Sleidinge</option>
<option value="Slijpe">Slijpe</option>
<option value="Slins">Slins</option>
<option value="Sluizen">Sluizen</option>
<option value="Smeerebbe-Vloerzegem">Smeerebbe-Vloerzegem</option>
<option value="Smetlede">Smetlede</option>
<option value="Smuid">Smuid</option>
<option value="Snaaskerke">Snaaskerke</option>
<option value="Snellegem">Snellegem</option>
<option value="Soheit-Tinlot">Soheit-Tinlot</option>
<option value="Sohier">Sohier</option>
<option value="Soignies">Soignies</option>
<option value="Soiron">Soiron</option>
<option value="Solre-Saint-Géry">Solre-Saint-Géry</option>
<option value="Solre-sur-Sambre">Solre-sur-Sambre</option>
<option value="Sombreffe">Sombreffe</option>
<option value="Somme-Leuze">Somme-Leuze</option>
<option value="Sommethonne">Sommethonne</option>
<option value="Sommiére">Sommiére</option>
<option value="Somzée">Somzée</option>
<option value="Sorée">Sorée</option>
<option value="Sorinne-la-Longue">Sorinne-la-Longue</option>
<option value="Sorinnes">Sorinnes</option>
<option value="Sosoye">Sosoye</option>
<option value="Sougné-Remouchamps">Sougné-Remouchamps</option>
<option value="Soulme">Soulme</option>
<option value="Soumagne">Soumagne</option>
<option value="Soumoy">Soumoy</option>
<option value="Sourbrodt">Sourbrodt</option>
<option value="Souvret">Souvret</option>
<option value="Sovet">Sovet</option>
<option value="Soy">Soy</option>
<option value="Soye (Nam.)">Soye (Nam.)</option>
<option value="Spa">Spa</option>
<option value="Spalbeek">Spalbeek</option>
<option value="Spiennes">Spiennes</option>
<option value="Spiere">Spiere</option>
<option value="Spiere-Helkijn">Spiere-Helkijn</option>
<option value="Spontin">Spontin</option>
<option value="Sprimont">Sprimont</option>
<option value="Spy">Spy</option>
<option value="Stabroek">Stabroek</option>
<option value="Staden">Staden</option>
<option value="talhille">Stalhille</option>
<option value="Stambruges">Stambruges</option>
<option value="Stave">Stave</option>
<option value="Stavele">Stavele</option>
<option value="Stavelot">Stavelot</option>
<option value="Steendorp">Steendorp</option>
<option value="Steenhuffel">Steenhuffel</option>
<option value="Steenhuize-Wijnhuize">Steenhuize-Wijnhuize</option>
<option value="Steenkerke (W.-VL.)">Steenkerke (W.-VL.)</option>
<option value="Steenokkerzeel">Steenokkerzeel</option>
<option value="Stekene">Stekene</option>
<option value="Stembert">Stembert</option>
<option value="Stene">Stene</option>
<option value="Sterrebeek">Sterrebeek</option>
<option value="Stevoort">Stevoort</option>
<option value="Stokkem">Stokkem</option>
<option value="Stokrooie">Stokrooie</option>
<option value="Stoumont">Stoumont</option>
<option value="Straimont">Straimont</option>
<option value="Strée (Ht.)">Strée (Ht.)</option>
<option value="Strée-lez-Huy">Strée-lez-Huy</option>
<option value="Strépy-Bracquegnies">Strépy-Bracquegnies</option>
<option value="Strijpen">Strijpen</option>
<option value="Strijtem">Strijtem</option>
<option value="Strombeek-Bever">Strombeek-Bever</option>
<option value="Stuivekenskerke">Stuivekenskerke</option>
<option value="uarlée">Suarlée</option>
<option value="Sugny">Sugny</option>
<option value="Surice">Surice</option>
<option value="Suxy">Suxy</option>
<option value="Tailles">Tailles</option>
<option value="Taintignies">Taintignies</option>
<option value="Tamines">Tamines</option>
<option value="Tarcienne">Tarcienne</option>
<option value="avier">Tavier</option>
<option value="Taviers (Nam.)">Taviers (Nam.)</option>
<option value="Tavigny">Tavigny</option>
<option value="Tellin">Tellin</option>
<option value="Templeuve">Templeuve</option>
<option value="Temploux">Temploux</option>
<option value="Temse">Temse</option>
<option value="Tenneville">Tenneville</option>
<option value="Teralfene">Teralfene</option>
<option value="Terhagen">Terhagen</option>
<option value="Termes">Termes</option>
<option value="Ternat">Ternat</option>
<option value="Tertre">Tertre</option>
<option value="Tervuren">Tervuren</option>
<option value="Terwagne">Terwagne</option>
<option value="Tessenderlo">Tessenderlo</option>
<option value="Testelt">Testelt</option>
<option value="Teuven">Teuven</option>
<option value="Theux">Theux</option>
<option value="Thiaumont">Thiaumont</option>
<option value="Thieu">Thieu</option>
<option value="Thieulain">Thieulain</option>
<option value="Thieusies">Thieusies</option>
<option value="Thiméon">Thiméon</option>
<option value="Thimister">Thimister</option>
<option value="Thimister-Clermont">Thimister-Clermont</option>
<option value="Thimougies">Thimougies</option>
<option value="Thines">Thines</option>
<option value="Thirimont">Thirimont</option>
<option value="Thisnes">Thisnes</option>
<option value="Thommen">Thommen</option>
<option value="Thon">Thon</option>
<option value="Thorembais-les-Béguines">Thorembais-les-Béguines</option>
<option value="Thorembais-Saint-Trond">Thorembais-Saint-Trond</option>
<option value="Thoricourt">Thoricourt</option>
<option value="Thuillies">Thuillies</option>
<option value="Thuin">Thuin</option>
<option value="Thulin">Thulin</option>
<option value="Thumaide">Thumaide</option>
<option value="Thy-le-Bauduin">Thy-le-Bauduin</option>
<option value="Thy-le-Château">Thy-le-Château</option>
<option value="Thynes">Thynes</option>
<option value="Thys">Thys</option>
<option value="Tiegem">Tiegem</option>
<option value="Tielen">Tielen</option>
<option value="Tielrode">Tielrode</option>
<option value="Tielt">Tielt</option>
<option value="Tielt (Bt.)">Tielt (Bt.)</option>
<option value="Tienen">Tienen</option>
<option value="Tignée">Tignée</option>
<option value="Tihange">Tihange</option>
<option value="Tildonk">Tildonk</option>
<option value="Tilff">Tilff</option>
<option value="Tillet">Tillet</option>
<option value="Tilleur">Tilleur</option>
<option value="Tillier">Tillier</option>
<option value="Tilly">Tilly</option>
<option value="Tinlot">Tinlot</option>
<option value="Tintange">Tintange</option>
<option value="Tintigny">Tintigny</option>
<option value="Tisselt">Tisselt</option>
<option value="Toernich">Toernich</option>
<option value="Tohogne">Tohogne</option>
<option value="Tollembeek">Tollembeek</option>
<option value="Tongeren">Tongeren</option>
<option value="Tongerlo (Antw.)">Tongerlo (Antw.)</option>
<option value="Tongerlo (Limb.)">Tongerlo (Limb.)</option>
<option value="Tongre-Notre-Dame">Tongre-Notre-Dame</option>
<option value="Tongre-Saint-Martin">Tongre-Saint-Martin</option>
<option value="Tongrinne">Tongrinne</option>
<option value="Tontelange">Tontelange</option>
<option value="Torgny">Torgny</option>
<option value="Torhout">Torhout</option>
<option value="Tourinne (Lg.)">Tourinne (Lg.)</option>
<option value="Tourinnes-la-Grosse">Tourinnes-la-Grosse</option>
<option value="Tourinnes-Saint-Lambert">Tourinnes-Saint-Lambert</option>
<option value="Tournai">Tournai</option>
<option value="Tournay">Tournay</option>
<option value="Tourpes">Tourpes</option>
<option value="Transinne">Transinne</option>
<option value="Trazegnies">Trazegnies</option>
<option value="Treignes">Treignes</option>
<option value="Trembleur">Trembleur</option>
<option value="Tremelo">Tremelo</option>
<option value="Triviéres">Triviéres</option>
<option value="Trognée">Trognée</option>
<option value="Trois-Ponts">Trois-Ponts</option>
<option value="Trooz">Trooz</option>
<option value="Tubize">Tubize</option>
<option value="Turnhout">Turnhout</option>
<option value="Ucimont">Ucimont</option>
<option value="Uikhoven">Uikhoven</option>
<option value="Uitbergen">Uitbergen</option>
<option value="Uitkerke">Uitkerke</option>
<option value="Ukkel">Ukkel</option>
<option value="Ulbeek">Ulbeek</option>
<option value="Upigny">Upigny</option>
<option value="Ursel">Ursel</option>
<option value="Vaalbeek">Vaalbeek</option>
<option value="Val-Meer">Val-Meer</option>
<option value="Vance">Vance</option>
<option value="Varendonk">Varendonk</option>
<option value="Varsenare">Varsenare</option>
<option value="Vaucelles">Vaucelles</option>
<option value="Vaulx (Tournai)">Vaulx (Tournai)</option>
<option value="Vaulx-lez-Chimay">Vaulx-lez-Chimay</option>
<option value="Vaux-Chavanne">Vaux-Chavanne</option>
<option value="Vaux-et-Borset">Vaux-et-Borset</option>
<option value="Vaux-lez-Rosiéres">Vaux-lez-Rosiéres</option>
<option value="Vaux-sous-Chévremont">Vaux-sous-Chévremont</option>
<option value="Vaux-sur-Sure">Vaux-sur-Sure</option>
<option value="Vechmaal">Vechmaal</option>
<option value="Vedrin">Vedrin</option>
<option value="Veerle">Veerle</option>
<option value="Velaines">Velaines</option>
<option value="Velaine-sur-Sambre">Velaine-sur-Sambre</option>
<option value="Veldegem">Veldegem</option>
<option value="Veldwezelt">Veldwezelt</option>
<option value="Vellereille-les-Brayeux">Vellereille-les-Brayeux</option>
<option value="Vellereille-le-Sec">Vellereille-le-Sec</option>
<option value="Velm">Velm</option>
<option value="Velroux">Velroux</option>
<option value="Veltem-Beisem">Veltem-Beisem</option>
<option value="Velzeke-Ruddershove">Velzeke-Ruddershove</option>
<option value="Vencimont">Vencimont</option>
<option value="Vergnies">Vergnies</option>
<option value="Verlaine">Verlaine</option>
<option value="Verlée">Verlée</option>
<option value="Verrebroek">Verrebroek</option>
<option value="Vertrijk">Vertrijk</option>
<option value="Verviers">Verviers</option>
<option value="Vesqueville">Vesqueville</option>
<option value="Veulen">Veulen</option>
<option value="Veurne">Veurne</option>
<option value="Vezin">Vezin</option>
<option value="Vezon">Vezon</option>
<option value="Viane">Viane</option>
<option value="Vichte">Vichte</option>
<option value="Vielsalm">Vielsalm</option>
<option value="Viemme">Viemme</option>
<option value="Viersel">Viersel</option>
<option value="Vierset-Barse">Vierset-Barse</option>
<option value="Vierves-sur-Viroin">Vierves-sur-Viroin</option>
<option value="Viesville">Viesville</option>
<option value="Vieux-Genappe">Vieux-Genappe</option>
<option value="Vieuxville">Vieuxville</option>
<option value="Vieux-Waleffe">Vieux-Waleffe</option>
<option value="Villance">Villance</option>
<option value="Ville-en-Hesbaye">Ville-en-Hesbaye</option>
<option value="Ville-Pommeroeul">Ville-Pommeroeul</option>
<option value="Villerot">Villerot</option>
<option value="Villers-aux-Tours">Villers-aux-Tours</option>
<option value="Villers-Deux-Eglises">Villers-Deux-Eglises</option>
<option value="Villers-devant-Orval">Villers-devant-Orval</option>
<option value="Villers-en-Fagne">Villers-en-Fagne</option>
<option value="Villers-la-Bonne-Eau">Villers-la-Bonne-Eau</option>
<option value="Villers-la-Loue">Villers-la-Loue</option>
<option value="Villers-la-Tour">Villers-la-Tour</option>
<option value="Villers-la-Ville">Villers-la-Ville</option>
<option value="illers-le-Bouillet">Villers-le-Bouillet</option>
<option value="Villers-le-Gambon">Villers-le-Gambon</option>
<option value="Villers-le-Peuplier">Villers-le-Peuplier</option>
<option value="Villers-le-Temple">Villers-le-Temple</option>
<option value="Villers-l'Evêque">Villers-l'Evêque</option>
<option value="Villers-lez-Heest">Villers-lez-Heest</option>
<option value="Villers-Notre-Dam ">Villers-Notre-Dame</option>
<option value="Villers-Perwin">Villers-Perwin</option>
<option value="Villers-Poterie">Villers-Poterie</option>
<option value="Villers-Saint-Amand">Villers-Saint-Amand</option>
<option value="Villers-Sainte-Gertrude">Villers-Sainte-Gertrude</option>
<option value="Villers-Saint-Ghislain">Villers-Saint-Ghislain</option>
<option value="Villers-Saint-Siméon">Villers-Saint-Siméon</option>
<option value="Villers-sur-Lesse">Villers-sur-Lesse</option>
<option value="Villers-sur-Semois">Villers-sur-Semois</option>
<option value="Ville-sur-Haine (Mons)">Ville-sur-Haine (Mons)</option>
<option value="Ville-sur-Haine(Le Roeulx)">Ville-sur-Haine(Le Roeulx)</option>
<option value="Vilvoorde">Vilvoorde</option>
<option value="Vinalmont">Vinalmont</option>
<option value="Vinderhoute">Vinderhoute</option>
<option value="Vinkem">Vinkem</option>
<option value="Vinkt">Vinkt</option>
<option value="Virelles">Virelles</option>
<option value="Virginal-Samme">Virginal-Samme</option>
<option value="Viroinval">Viroinval</option>
<option value="Virton">Virton</option>
<option value="Visé">Visé</option>
<option value="Vissenaken">Vissenaken</option>
<option value="Vitrival">Vitrival</option>
<option value="Vivegnis">Vivegnis</option>
<option value="Vivy">Vivy</option>
<option value="Vladslo">Vladslo</option>
<option value="Vlamertinge">Vlamertinge</option>
<option value="Vlekkem">Vlekkem</option>
<option value="Vleteren">Vleteren</option>
<option value="Vlezenbeek">Vlezenbeek</option>
<option value="Vliermaal">Vliermaal</option>
<option value="Vliermaalroot">Vliermaalroot</option>
<option value="Vlierzele">Vlierzele</option>
<option value="Vlijtingen">Vlijtingen</option>
<option value="Vlimmeren">Vlimmeren</option>
<option value="Vlissegem">Vlissegem</option>
<option value="Vloesberg">Vloesberg</option>
<option value="Vodecée">Vodecée</option>
<option value="Vodelée">Vodelée</option>
<option value="Voeren">Voeren</option>
<option value="Vogenée">Vogenée</option>
<option value="Volkegem">Volkegem</option>
<option value="Vollezele">Vollezele</option>
<option value="Vonêche">Vonêche</option>
<option value="Voorde">Voorde</option>
<option value="Voormezele">Voormezele</option>
<option value="Voort">Voort</option>
<option value="Voroux-Goreux">Voroux-Goreux</option>
<option value="Voroux-lez-Liers">Voroux-lez-Liers</option>
<option value="Vorselaar">Vorselaar</option>
<option value="Vorsen">Vorsen</option>
<option value="Vorst">Vorst</option>
<option value="Vorst (Kempen)">Vorst (Kempen)</option>
<option value="Vosselaar">Vosselaar</option>
<option value="Vosselare">Vosselare</option>
<option value="Vossem">Vossem</option>
<option value="Vottem">Vottem</option>
<option value="Vrasene">Vrasene</option>
<option value="Vremde">Vremde</option>
<option value="Vreren">Vreren</option>
<option value="Vresse-sur-Semois">Vresse-sur-Semois</option>
<option value="Vroenhoven">Vroenhoven</option>
<option value="Vucht">Vucht</option>
<option value="Vurste">Vurste</option>
<option value="Vyle-et-Tharoul">Vyle-et-Tharoul</option>
<option value="Waanrode">Waanrode</option>
<option value="Waarbeke">Waarbeke</option>
<option value="Waardamme">Waardamme</option>
<option value="Waarloos">Waarloos</option>
<option value="Waarmaarde">Waarmaarde</option>
<option value="Waarschoot">Waarschoot</option>
<option value="Waasmont">Waasmont</option>
<option value="Waasmunster">Waasmunster</option>
<option value="Waasten">Waasten</option>
<option value="Wachtebeke">Wachtebeke</option>
<option value="Wadelincourt">Wadelincourt</option>
<option value="Wagnelée">Wagnelée</option>
<option value="Waha">Waha</option>
<option value="Waillet">Waillet</option>
<option value="Waimes">Waimes</option>
<option value="Wakken">Wakken</option>
<option value="Walcourt">Walcourt</option>
<option value="Walem">Walem</option>
<option value="Walhain">Walhain</option>
<option value="Walhain-Saint-Paul">Walhain-Saint-Paul</option>
<option value="Walhorn">Walhorn</option>
<option value="Walsbets">Walsbets</option>
<option value="Walshoutem">Walshoutem</option>
<option value="Waltwilder">Waltwilder</option>
<option value="Wambeek">Wambeek</option>
<option value="Wancennes">Wancennes</option>
<option value="Wandre">Wandre</option>
<option value="Wanfercée-Baulet">Wanfercée-Baulet</option>
<option value="Wange">Wange</option>
<option value="Wangenies">Wangenies</option>
<option value="Wanlin">Wanlin</option>
<option value="Wanne">Wanne</option>
<option value="Wannebecq">Wannebecq</option>
<option value="Wannegem-Lede">Wannegem-Lede</option>
<option value="Wansin">Wansin</option>
<option value="Wanze">Wanze</option>
<option value="Wanzele">Wanzele</option>
<option value="Warchin">Warchin</option>
<option value="Warcoing">Warcoing</option>
<option value="Wardin">Wardin</option>
<option value="Waregem">Waregem</option>
<option value="Waremme">Waremme</option>
<option value="Waret-la-Chaussée">Waret-la-Chaussée</option>
<option value="Waret-l'Evêque">Waret-l'Evêque</option>
<option value="Warisoulx">Warisoulx</option>
<option value="Warnant">Warnant</option>
<option value="Warnant-Dreye">Warnant-Dreye</option>
<option value="Warneton">Warneton</option>
<option value="Warquignies">Warquignies</option>
<option value="Warsage">Warsage</option>
<option value="Warzée">Warzée</option>
<option value="Wasmes">Wasmes</option>
<option value="Wasmes-Audemez-Briffoeil">Wasmes-Audemez-Briffoeil</option>
<option value="Wasmuel">Wasmuel</option>
<option value="Wasseiges">Wasseiges</option>
<option value="Waterland-Oudeman">Waterland-Oudeman</option>
<option value="Waterloo">Waterloo</option>
<option value="Watermaal-Bosvoorde">Watermaal-Bosvoorde</option>
<option value="Watervliet">Watervliet</option>
<option value="Watou">Watou</option>
<option value="Wattripont">Wattripont</option>
<option value="Waudrez">Waudrez</option>
<option value="Waulsort">Waulsort</option>
<option value="Wauthier-Braine">Wauthier-Braine</option>
<option value="Wavre">Wavre</option>
<option value="Wavreille">Wavreille</option>
<option value="Wayaux">Wayaux</option>
<option value="Ways">Ways</option>
<option value="Webbekom">Webbekom</option>
<option value="Wechelderzande">Wechelderzande</option>
<option value="Weelde">Weelde</option>
<option value="Weerde">Weerde</option>
<option value="Weert">Weert</option>
<option value="Wegnez">Wegnez</option>
<option value="Weillen">Weillen</option>
<option value="Weismes">Weismes</option>
<option value="Welden">Welden</option>
<option value="Welkenraedt">Welkenraedt</option>
<option value="Welle">Welle</option>
<option value="Wellen">Wellen</option>
<option value="Wellin">Wellin</option>
<option value="Wemmel">Wemmel</option>
<option value="Wenduine">Wenduine</option>
<option value="Wépion">Wépion</option>
<option value="Werbomont">Werbomont</option>
<option value="Werchter">Werchter</option>
<option value="Wéris">Wéris</option>
<option value="Werken">Werken</option>
<option value="Werm">Werm</option>
<option value="Wervik">Wervik</option>
<option value="Wespelaar">Wespelaar</option>
<option value="Westende">Westende</option>
<option value="Westerlo">Westerlo</option>
<option value="Westkapelle">Westkapelle</option>
<option value="Westkerke">Westkerke</option>
<option value="Westmalle">Westmalle</option>
<option value="Westmeerbeek">Westmeerbeek</option>
<option value="Westouter">Westouter</option>
<option value="Westrem">Westrem</option>
<option value="Westrozebeke">Westrozebeke</option>
<option value="Westvleteren">Westvleteren</option>
<option value="Wetteren">Wetteren</option>
<option value="Wevelgem">Wevelgem</option>
<option value="Wezemaal">Wezemaal</option>
<option value="Wezembeek-Oppem">Wezembeek-Oppem</option>
<option value="Wezeren">Wezeren</option>
<option value="Wez-Velvain">Wez-Velvain</option>
<option value="Wibrin">Wibrin</option>
<option value="Wichelen">Wichelen</option>
<option value="Widooie">Widooie</option>
<option value="Wiekevorst">Wiekevorst</option>
<option value="Wielsbeke">Wielsbeke</option>
<option value="Wierde">Wierde</option>
<option value="Wiers">Wiers</option>
<option value="Wiesme">Wiesme</option>
<option value="Wieze">Wieze</option>
<option value="Wihéries">Wihéries</option>
<option value="Wihogne">Wihogne</option>
<option value="Wijchmaal">Wijchmaal</option>
<option value="Wijer">Wijer</option>
<option value="Wijgmaal (Bt.)">Wijgmaal (Bt.)</option>
<option value="Wijnegem">Wijnegem</option>
<option value="Wijshagen">Wijshagen</option>
<option value="Wijtschate">Wijtschate</option>
<option value="Wilderen">Wilderen</option>
<option value="Willaupuis">Willaupuis</option>
<option value="Willebringen">Willebringen</option>
<option value="Willebroek">Willebroek</option>
<option value="Willemeau">Willemeau</option>
<option value="Willerzie">Willerzie</option>
<option value="Wilrijk (Antwerpen)">Wilrijk (Antwerpen)</option>
<option value="Wilsele">Wilsele</option>
<option value="Wilskerke">Wilskerke</option>
<option value="Wimmertingen">Wimmertingen</option>
<option value="Winenne">Winenne</option>
<option value="Wingene">Wingene</option>
<option value="Winksele">Winksele</option>
<option value="Wintershoven">Wintershoven</option>
<option value="Witry">Witry</option>
<option value="Wodecq">Wodecq</option>
<option value="Woesten">Woesten</option>

<option value="Wolkrange">Wolkrange</option>
<option value="Wolvertem">Wolvertem</option>
<option value="Wommelgem">Wommelgem</option>
<option value="Wommersom">Wommersom</option>
<option value="Wonck">Wonck</option>
<option value="Wondelgem">Wondelgem</option>
<option value="Wontergem">Wontergem</option>
<option value="Wortegem">Wortegem</option>
<option value="Wortegem-Petegem">Wortegem-Petegem</option>
<option value="Wortel">Wortel</option>
<option value="Woubrechtegem">Woubrechtegem</option>
<option value="Woumen">Woumen</option>
<option value="Wulpen">Wulpen</option>
<option value="Wulvergem">Wulvergem</option>
<option value="Wulveringem">Wulveringem</option>
<option value="Wuustwezel">Wuustwezel</option>
<option value="Xhendelesse">Xhendelesse</option>
<option value="Xhendremael">Xhendremael</option>
<option value="Xhoris">Xhoris</option>
<option value="Yernée-Fraineux">Yernée-Fraineux</option>
<option value="Yves-Gomezée">Yves-Gomezée</option>
<option value="Yvoir">Yvoir</option>
<option value="Zaffelare">Zaffelare</option>
<option value="Zandbergen">Zandbergen</option>
<option value="Zande">Zande</option>
<option value="Zandhoven">Zandhoven</option>
<option value="Zandvliet">Zandvliet</option>
<option value="Zandvoorde (Oostende)">Zandvoorde (Oostende)</option>
<option value="Zandvoorde (Zonnebeke)">Zandvoorde (Zonnebeke)</option>
<option value="Zarlardinge">Zarlardinge</option>
<option value="Zarren">Zarren</option>
<option value="Zaventem">Zaventem</option>
<option value="Zedelgem">Zedelgem</option>
<option value="Zeebrugge (Brugge)">Zeebrugge (Brugge)</option>
<option value="Zegelsem">Zegelsem</option>
<option value="Zele">Zele</option>
<option value="Zelem">Zelem</option>
<option value="Zellik">Zellik</option>
<option value="Zelzate">Zelzate</option>
<option value="Zemst">Zemst</option>
<option value="Zepperen">Zepperen</option>
<option value="Zerkegem">Zerkegem</option>
<option value="Zétrud-Lumay">Zétrud-Lumay</option>
<option value="Zevekote">Zevekote</option>
<option value="Zeveneken">Zeveneken</option>
<option value="Zeveren">Zeveren</option>
<option value="Zevergem">Zevergem</option>
<option value="Zichem">Zichem</option>
<option value="Zichen-Zussen-Bolder">Zichen-Zussen-Bolder</option>
<option value="Zillebeke">Zillebeke</option>
<option value="Zingem">Zingem</option>
<option value="Zoerle-Parwijs">Zoerle-Parwijs</option>
<option value="Zoersel">Zoersel</option>
<option value="Zolder">Zolder</option>
<option value="Zomergem">Zomergem</option>
<option value="Zonhoven">Zonhoven</option>
<option value="Zonnebeke">Zonnebeke</option>
<option value="Zonnegem">Zonnegem</option>
<option value="Zottegem">Zottegem</option>
<option value="Zoutenaaie">Zoutenaaie</option>
<option value="Zoutleeuw">Zoutleeuw</option>
<option value="Zuidschote">Zuidschote</option>
<option value="Zuienkerke">Zuienkerke</option>
<option value="Zulte">Zulte</option>
<option value="Zulzeke">Zulzeke</option>
<option value="Zutendaal">Zutendaal</option>
<option value="Zwalm">Zwalm</option>
<option value="Zwevegem">Zwevegem</option>
<option value="Zwevezele">Zwevezele</option>
<option value="Zwijnaarde">Zwijnaarde</option>
<option value="Zwijndrecht">Zwijndrecht</option>
