<option value="Nordjylland">Nordjylland</option>
<option value="Midtjylland">Midtjylland</option>
<option value="Østjylland">Østjylland</option>
<option value="Vestjylland">Vestjylland</option>
<option value="Sønderjylland">Sønderjylland</option>
<option value="Fyn">Fyn</option>
<option value="København">København</option>
<option value="København">Storkøbenhavn</option>
<option value="Nordsjælland">Nordsjælland</option>
<option value="Sydsjælland">Sydsjælland</option>
<option value="Vestsjælland">Vestsjælland</option>
<option value="Nordsjælland">Lolland/Falster</option>
<option value="Bornholm">Bornholm</option>
<option value="Andet">Andet</option>