<option value="Akershus">Akershus</option>
<option value="Aust-Agder">Aust-Agder</option>
<option value="Buskerud">Buskerud</option>
<option value="Finnmark">Finnmark</option>
<option value="Hedmark">Hedmark</option>
<option value="Hordaland">Hordaland</option>
<option value="Møre og Romsdal">Møre og Romsdal</option>
<option value="Nordland">Nordland</option>
<option value="Nord-Trøndelag">Nord-Trøndelag</option>
<option value="Oppland">Oppland</option>
<option value="Rogaland">Rogaland</option>
<option value="Sogn og Fjordane">Sogn og Fjordane</option>
<option value="Sør-Trøndelag">Sør-Trøndelag</option>
<option value="Telemark">Telemark</option>
<option value="Troms">Troms</option>
<option value="Vest-Agder">Vest-Agder</option>
<option value="Vestfold">Vestfold</option>
<option value="Østfold">Østfold</option>
