<option value="AB - Stockholm">AB - Stockholm</option>
<option value="AC - Västerbotten">AC - Västerbotten</option>
<option value="BD - Norrbotten">BD - Norrbotten</option>
<option value="C - Uppsala">C - Uppsala</option>
<option value="D - Södermanland">D - Södermanland</option>
<option value="E - Östergötland">E - Östergötland</option>
<option value="F - Jönköping">F - Jönköping</option>
<option value="G - Kronoberg">G - Kronoberg</option>
<option value="H - Kalmar">H - Kalmar</option>
<option value="I - Gotland">I - Gotland</option>
<option value="K - Blekinge">K - Blekinge</option>
<option value="M - Skåne">M - Skåne</option>
<option value="N - Halland">N - Halland</option>
<option value="O - Västra Götaland">O - Västra Götaland</option>
<option value="S - Värmland">S - Värmland</option>
<option value="T - Örebro">T - Örebro</option>
<option value="U - Västmanland">U - Västmanland</option>
<option value="W - Dalarna">W - Dalarna</option>
<option value="X - Gävleborg">X - Gävleborg</option>
<option value="Y - Västernorrland">Y - Västernorrland</option>
<option value="Z - Jämtland">Z - Jämtland</option>