mv 1-3jn.htm.bak 1-3jn.htm
mv 1COR.htm.bak 1COR.htm
mv 1pet.htm.bak 1pet.htm
mv 1thess.htm.bak 1thess.htm
mv 1tim.htm.bak 1tim.htm
mv 2COR.htm.bak 2COR.htm
mv 2pet.htm.bak 2pet.htm
mv 2thess.htm.bak 2thess.htm
mv 2tim-titus.htm.bak 2tim-titus.htm
mv ACTS.htm.bak ACTS.htm
mv EPH.htm.bak EPH.htm
mv GAL.htm.bak GAL.htm
mv Introduct.htm.bak Introduct.htm
mv JOHN.htm.bak JOHN.htm
mv JUDE.htm.bak JUDE.htm
mv LUKE.htm.bak LUKE.htm
mv MARK.htm.bak MARK.htm
mv MATTHEW.htm.bak MATTHEW.htm
mv ROMANS.htm.bak ROMANS.htm
mv col.htm.bak col.htm
mv heb.htm.bak heb.htm
mv james.htm.bak james.htm
mv ntintro.htm.bak ntintro.htm
mv phil.htm.bak phil.htm
mv philemon.htm.bak philemon.htm
mv rev.htm.bak rev.htm
