INSERT INTO smilies VALUES ( ':1)', 'alien2.gif', 'invader');
INSERT INTO smilies VALUES ( ':2)', 'kitty.gif', 'Bastard Kitty');
INSERT INTO smilies VALUES ( ':3)', 'heart.gif', 'Heart1');
INSERT INTO smilies VALUES ( ':4)', 'rainbow.gif', 'tie died');
INSERT INTO smilies VALUES ( ':5)', 'el.gif', 'Embarrassed');
INSERT INTO smilies VALUES ( ':6)', 'pumpkin2.gif', 'Helloween');
INSERT INTO smilies VALUES ( ':7)', 'private.gif', 'Secret');
INSERT INTO smilies VALUES ( ':x)', 'xmas.gif', 'Christmas');
INSERT INTO smilies VALUES ( ':9)', 'kiss.gif', 'Kiss, Kiss');
INSERT INTO smilies VALUES ( ':1]', 'karate.gif', 'Karate');
INSERT INTO smilies VALUES ( ':2]', 'cold.gif', 'Cold');
INSERT INTO smilies VALUES ( ':3]', 'devil.gif', 'Devil');
INSERT INTO smilies VALUES ( ':4]', 'tongue2.gif', 'So Nyah!');
INSERT INTO smilies VALUES ( ':5]', 'redhot.gif', 'Red Hot');
INSERT INTO smilies VALUES ( ':6]', 'smash.gif', 'Smash!');
INSERT INTO smilies VALUES ( ':7]', 'frosty.gif', 'Frosty');
INSERT INTO smilies VALUES ( ':8]', 'confused2.gif', 'Confused again');
INSERT INTO smilies VALUES ( ':9]', 'kaioken.gif', 'KAI');
INSERT INTO smilies VALUES ( ':1}', 'vampire.gif', 'Vampire');
INSERT INTO smilies VALUES ( ':2}', 'splat.gif', 'Splat');
INSERT INTO smilies VALUES ( ':3}', 'rwb.gif', 'Flag Smiley');
INSERT INTO smilies VALUES ( ':4}', 'FRlol.gif', 'LOL2');
INSERT INTO smilies VALUES ( ':5}', 'goodbad.gif', 'Good / Bad');
INSERT INTO smilies VALUES ( ':6}', 'eek2.gif', 'EEEEK');
INSERT INTO smilies VALUES ( ':7}', 'dodgy.gif', 'Dodgy');
INSERT INTO smilies VALUES ( ':8}', 'bawling.gif', 'Bawling');
INSERT INTO smilies VALUES ( ':9}', 'party.gif', 'Party on, Garth!');
INSERT INTO smilies VALUES ( ':ni', 'nighty.gif', 'Nightey, Night!');
INSERT INTO smilies VALUES ( ':wa', 'wavey.gif', 'Wave!');
INSERT INTO smilies VALUES ( ':pa', 'patty.gif', 'Patty');
INSERT INTO smilies VALUES ( ':al', 'alarm.gif', 'Alarm');
INSERT INTO smilies VALUES ( ':ba', 'barf.gif', 'Barf!');
INSERT INTO smilies VALUES ( ':bd', 'birthday.gif', 'Birthday');
INSERT INTO smilies VALUES ( ':bu', 'bubble.gif', 'bubble');
INSERT INTO smilies VALUES ( ':ca', 'cat.gif', 'Kitty');
INSERT INTO smilies VALUES ( ':ce', 'censored.gif', 'Censor');
INSERT INTO smilies VALUES ( ':ch', 'cheers.gif', 'Cheers');
INSERT INTO smilies VALUES ( ':co', 'cowboy.gif', 'Cowboy');
INSERT INTO smilies VALUES ( ':da', 'dance.gif', 'Dancing');
INSERT INTO smilies VALUES ( ':gr', 'dance1.gif', 'Dancing Stick');
INSERT INTO smilies VALUES ( ':du', 'dunce.gif', 'Dunce');
INSERT INTO smilies VALUES ( ':fi', 'finger.gif', 'Bird');
INSERT INTO smilies VALUES ( ':fe', 'flame.gif', 'Flame');
INSERT INTO smilies VALUES ( ':fg', 'flaming.gif', 'Flaming');
INSERT INTO smilies VALUES ( ':fl', 'flower2.gif', 'Flower #2');
INSERT INTO smilies VALUES ( ':hi', 'hippie.gif', 'Hippie');
INSERT INTO smilies VALUES ( ':jo', 'joker.gif', 'Jester');
INSERT INTO smilies VALUES ( ':kn', 'knight.gif', 'Knight');
INSERT INTO smilies VALUES ( ':ko', 'koolaid.gif', 'KoolAid');
INSERT INTO smilies VALUES ( ':lo', 'looney.gif', 'Looney');
INSERT INTO smilies VALUES ( ':pi', 'pimp.gif', 'Pimp');
INSERT INTO smilies VALUES ( ':fy', 'mfinger.gif', 'Monkey Bird');
INSERT INTO smilies VALUES ( ':pu', 'pukeface.gif', 'Puke');
INSERT INTO smilies VALUES ( ':no', 'no.gif', 'NO!');
INSERT INTO smilies VALUES ( ':ro', 'rosie.gif', 'Rosy Cheeks');
INSERT INTO smilies VALUES ( ':sh', 'shudder.gif', 'Shudder');
INSERT INTO smilies VALUES ( ':si', 'sick.gif', 'Sick');
INSERT INTO smilies VALUES ( ':sm', 'smoker.gif', 'Smokin\'');
INSERT INTO smilies VALUES ( ':se', 'sperm.gif', 'Sperm');
INSERT INTO smilies VALUES ( ':to', 'tomato.gif', 'tomato');
INSERT INTO smilies VALUES ( ':tu', 'tut.gif', 'King Tut');
INSERT INTO smilies VALUES ( ':ty', 'type.gif', 'Typing');
INSERT INTO smilies VALUES ( ':wh', 'whip.gif', 'Whip It!');
INSERT INTO smilies VALUES ( ':ja', 'whoa.gif', 'Jaw Dropping');